### ISSUE TITLE
[Epic] HTTP/2 performance

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#13750]
In 5.0 we want to make ASP.NET Core 's HTTP/2 performance something we can be proud of. HTTP/2 performance can be advertised as a reason to choose .NET

* [ ] https://github.com/aspnet/AspNetCore/issues/13745 Initial HTTP/2 perf investigation
* [ ] https://github.com/aspnet/AspNetCore/issues/13752 HTTP/2 Benchmarks

Identified issues (will grow):

* [x] https://github.com/aspnet/AspNetCore/issues/6192 Pool HTTP/2 Streams on the Http2Connection
* [x] https://github.com/aspnet/AspNetCore/issues/4761 Add HTTP/2 pseudo-headers as known headers
* [x] https://github.com/aspnet/AspNetCore/issues/11270 HTTP2: Send trailers with data
* [x] https://github.com/dotnet/aspnetcore/issues/19276 HTTP2: Reuse request and response Pipe
* [x] https://github.com/dotnet/aspnetcore/issues/19275 HTTP2: Header enumerator allocations

[All open HTTP2 and Perf issues](https://github.com/aspnet/AspNetCore/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3AHTTP2+label%3APerf)

@Tratcher @halter73 @davidfowl @shirhatti @JunTaoLuo

**Comment by jkotalik** [comment]
This is done for 5.0. Closing 😄
