### ISSUE TITLE
[EPIC] PR Benchmark Validation

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#14867]
- [x] Set up benchmark machine that [accepts jobs](https://github.com/aspnet/Benchmarks/blob/77d30bfce11fe065a80a65527e4b3bebd44d8fbe/src/JobConsumer/Program.cs)
- [x] Create console app that submits jobs.
- [x] A baseline job will also be submitted.
- [x] Harness using a ci.
~~- [ ] Set up an internal AzDo pipeline to submit job.~~
- [x] Report job results back to GitHub PR
- [x] Threat modeling
- [x] Support external PRs
- [x] Set up multiple benchmark machines, so we're not benchmarking against localhost.
- [x] Add scenarios. Allow longer/more runs.
- [x] Addd parameterization.
- [x] Add scripts to repo that does most of the setup including adding CRON jobs for you
- [ ] Have the JobConsumer wait on the client and server to redeploy before starting itself. This could probably be done by SSHing from the JobConsumer machine to the server and/or client machines.
- [ ] Format benchmark output as markdown table
  - Check that it looks good on mobile
- [ ] Trigger a pull and rebuild of PR benchmark infrastructure via a command from a GitHub comment
- [ ] "Fail" the pipeline if the benchmark scenario regresses too much. We likely will never actually gate a PR on this.

**Comment by dougbu** [comment]
This looks really old:grey_exclamation: @halter73 @sebastienros can the issue be summarily closed❔

**Comment by sebastienros** [comment]
I think it can be considered done, Stephen?
