### ISSUE TITLE
[Epic] Support MessagePack Hub Protocol in SignalR Java Client

### ISSUE THREAD

**Issue by anurse** [dotnet/aspnetcore#21022]
We should add support for MessagePack to the SignalR Java Client.

This will require:
* [x] https://github.com/dotnet/aspnetcore/issues/21107 Identifying and evaluating MessagePack libraries for Java
* [x] https://github.com/dotnet/aspnetcore/issues/21644 Building a Hub Protocol implementation for Java according to the spec (https://github.com/dotnet/aspnetcore/blob/master/src/SignalR/docs/specs/HubProtocol.md)
* [ ] ~~Adding functional tests for Java (we don't have any right now :S) to cover this and other scenarios like JSON.~~ Not part of this work item
