### ISSUE TITLE
[EPIC]: HTTPS and Certificate Handling in Kestrel

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#21512]
This epic tracks all the work required in Kestrel to improve certificate management.

- [ ] - Support specifying a full certificate chain in HttpsConnectionAdapterOptions - https://github.com/dotnet/aspnetcore/issues/21513
  - [x] - SSLStream should support taking a pre-validated immutable full certificate chain - https://github.com/dotnet/runtime/issues/35844 - https://github.com/dotnet/runtime/issues/37933
- [x] - Add support for PEM format SSL certificates - https://github.com/dotnet/aspnetcore/issues/4706
    - [x] https://github.com/dotnet/runtime/issues/31944
- [ ] - Add support for loading entire key chains from PFX and PEM files. https://github.com/dotnet/aspnetcore/issues/23623
- [x] - Consider support for SNI certificate selection from X509Store - https://github.com/dotnet/aspnetcore/issues/21300
- [x] - ServerCertificateSelector callback needs to be async - https://github.com/dotnet/aspnetcore/issues/20981
- [x] - Enable SslStream server options per-hostname - https://github.com/dotnet/runtime/issues/31097
- [x] - Support SNI via config - https://github.com/dotnet/aspnetcore/issues/15144
- [ ] OCSP Stapling Support - https://github.com/dotnet/aspnetcore/issues/4762
    - [ ] https://github.com/dotnet/runtime/issues/33377
- [ ] - ~Configure certificate by thumbprint - https://github.com/dotnet/aspnetcore/issues/4385~
    - > The problem with thumbprints is it'll allow you to choose an expired certificate. Using subject names is better because it will pull a valid one (assuming it exists), with the longest validity period. Thumbprint selection should die.
- [x] - Cache certificate validation results in Certificate Auth https://github.com/dotnet/aspnetcore/issues/12324
- [x] - Enable setting the ClientCertificateMode from an appsettings.json file - https://github.com/dotnet/aspnetcore/issues/18660

**Comment by davidfowl** [comment]
cc @wfurt @karelz @bartonjs

**Comment by blowdart** [comment]
Do you want to add caching of certificate validation for certificate auth? https://github.com/dotnet/aspnetcore/issues/12324

**Comment by davidfowl** [comment]
Yea let me add that

**Comment by blowdart** [comment]
I added it because you didn't :p

**Comment by blowdart** [comment]
![HItY](https://user-images.githubusercontent.com/796298/81728303-171f5000-943f-11ea-8044-43f775670447.gif)

**Comment by webprofusion-chrisc** [comment]
I don't know if it's already tracked (or considered out of scope) but a common pattern for certificate use is to fetch them from a broker such as a central cert service or secrets store (using any method - http api, ACME etc -  but this may be a very long async wait) then re-fetch and re-apply them as expiry looms. The local X509Store (if any) may just be considered a local cache. 

It would be ideal if a standard interface for cert request & renewal could be provided (with custom providers for specific scenarios/implementations). 

All domain/host certs have expiry (which can be hours away or weeks away, but will happen during app uptime), users may wish to start to request renewal after a fixed time period e.g. every 30 days or a set period before cert expiry, e.g. 48 hrs before expiry). Initial renewal failures may be transient but repeated failures require escalation.

Fetching may fail if the client no longer has permission to request the cert for that domain or other validation has failed, therefore the service would continue to use the expiring/expired certificate and retry etc. 

As a service may have multiple domain/port bindings, the state of a certificate will vary per binding (some may be closer to expiry than others, may be refreshed using other means). Certs may be issued by public CAs or internal CAs (per binding). This is somewhat related to #21300 and #20981 but not completely and is really just a question of whether this scenario should be a concern for the core framework or left entirely to third-party middleware.

**Comment by davidfowl** [comment]
That’s pretty much why we leave policy out of the framework and push users to a callback model. That will be what we enable before doing anything more advanced. We may be able to integrate more as we get a feel for what customers do with it and if it’s common enough and difficult, we could bake something in

**Comment by jkotalik** [comment]
Done for 5.0
