### ISSUE TITLE
Improve Blazor development experience through refactoring

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#21901]
As part of this effort we want to enable the following scenarios:
- [x] [`@code` refactor to code behind](https://github.com/dotnet/aspnetcore/issues/22239)
- [x] [Create component from unknown component looking tag. (Wouldn’t generate parameters)](https://github.com/dotnet/aspnetcore/issues/22307)
- [x] [Add using for component](https://github.com/dotnet/aspnetcore/issues/22308)
- [x] [Fully qualify component](https://github.com/dotnet/aspnetcore/issues/22309)
- [ ] [Directive attribute EventHandler generation](https://github.com/dotnet/aspnetcore/issues/22310)
- [ ] [Rename component](https://github.com/dotnet/aspnetcore/issues/22312)
- [ ] [File rename inferred rename component](https://github.com/dotnet/aspnetcore/issues/22313)
- [ ] [Rename parameter from `@code` nested C#](https://github.com/dotnet/aspnetcore/issues/22314)
- [ ] [Rename attribute parameter from markup](https://github.com/dotnet/aspnetcore/issues/22315)
