### ISSUE TITLE
Visual Studio Razor Smart Indent

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#21973]
This is a big rock issue that tracks the overall status of smart indent for Visual Studio. It has multiple parts but ultimately entails adding smart indent mechanics for typing scenarios in Razor

This includes:
- [x] [HTML tags inclusive of TagHelpers/Blazor components](https://github.com/dotnet/aspnetcore/issues/22119) AND [this](https://github.com/dotnet/aspnetcore/issues/21757):  2 days

Before:
```HTML
<strong>|</strong>
```
After hitting Enter
```HTML
<strong>
    |
</strong>
```
- [x] [C# curly braces](https://github.com/dotnet/aspnetcore/issues/22120) 4 days

Before:
```CSHTML
@if (true) {|}
```
After hitting Enter
```CSHTML
@if (true)
{
    |
}
```

- [x] [Razor statement braces](https://github.com/dotnet/aspnetcore/issues/22121) 4 days (overlapping C#)

Before:
```CSHTML
@{|}
```
After hitting Enter
```CSHTML
@{
    |
}
```

- [x] [Razor block directives](https://github.com/dotnet/aspnetcore/issues/22122) (4 days overlapping the above two)

Before:
```CSHTML
@code {|}
```
After hitting Enter
```CSHTML
@code {
    |
}
```

This is heavily dependent on Visual Studio's support for `OnEnterRules` and `OnTypeFormatting` and therefore will require lots of back and forth with the CoreEditor team to ensure we can land the feature.

**Comment by NTaylorMullen** [comment]
2 weeks estimated total
