### ISSUE TITLE
Visual Studio Razor Find all References - C# / HTML

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#21977]
This is a big rock issue that tracks the overall status of find all references for Visual Studio. It has multiple parts but ultimately entails adding the general "find all references" navigation action to pieces of the Razor document.

Given the size of this issue it will most likely not be completed in one release.

## 16.7-preview3-4
- [x] [Find all references from C# inside of a Razor file into & outside of a Razor file](https://github.com/dotnet/aspnetcore/issues/22003)
- [x] [Find all references from C# outside of a Razor file into a Razor file](https://github.com/dotnet/aspnetcore/issues/22004)
- [x] [FAR IProgress<T> Support](https://github.com/dotnet/aspnetcore/issues/22436)

The action of "find all referencing" outside of a Razor file into one was previously implemented in old-school Razor and the structure to make it possible in new-world Razor already exists.

**Comment by NTaylorMullen** [comment]
Estimated 5 days

**Comment by NTaylorMullen** [comment]
@TanayParikh as an FYI I know that Roslyn was planning to move to an IProgress<T> model for FAR. There's a good chance we'll need to ensure our FAR delegation can support that.

/cc @dibarbet

**Comment by dibarbet** [comment]
Yep, we previously used IProgress for FAR, but it was temporarily reverted due to an issue with IProgress ordering in liveshare.  We expect that to be fixed soon and we'll go back to using IProgress

**Comment by TanayParikh** [comment]
> but it was temporarily reverted

That would be https://github.com/dotnet/roslyn/pull/44283, correct?

**Comment by TanayParikh** [comment]
Updated the individual issues, but brief update here as well for tracking. The following components are blocked on various dependencies and will likely need to be pushed to preview 4. Will update when anything changes. 

- [ ] [Find all references from C# outside of a Razor file into a Razor file](https://github.com/dotnet/aspnetcore/issues/22004)
- [ ] [FAR IProgress<T> Support](https://github.com/dotnet/aspnetcore/issues/22436)

**Comment by TanayParikh** [comment]
Discussed offline with @NTaylorMullen. Closing this Big Rock out as the remaining issue (https://github.com/dotnet/aspnetcore/issues/22005) has an external dependency which isn't yet available. Will track that item separately going forward, and implement once possible.
