### ISSUE TITLE
Expose "Experimental Razor Editor" checkbox

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#21980]
Today Razor's experimental checkbox is only exposed in VSMaster builds. In order to expose this checkbox a few things need to be completed first.

### Bug fixes
- [x] Solution re-open should re-establish language server with proper workspace directory  - [External](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1127327)
- [x] Closing and re-opening documents https://github.com/dotnet/aspnetcore/issues/20629
- [x] [Reopening a file locally results in 0 HTML completions](https://github.com/dotnet/aspnetcore/issues/22791)
- [x] [Immediately interacting with Razor files when they're opened can cause crashes](https://github.com/dotnet/aspnetcore/issues/22837)

### Checkbox interactions

- [ ] [Enable Razor checkbox for release builds - 1 day](https://github.com/dotnet/aspnetcore/issues/22522)
- [x] [Closing/re-opening solution leaks, don't leak](https://github.com/dotnet/aspnetcore/issues/23054)
- [x] [Re-opening solutions will use the proper Razor editor indicated by checkbox (doesn't happen today). 3-5 days](https://github.com/dotnet/aspnetcore/issues/21270)
- [x] Investigate if we need to localize our checkbox information - 1 days - Do not need to localize to be on release chanel

**Comment by NTaylorMullen** [comment]
Estimated 2 weeks of work.

**Comment by NTaylorMullen** [comment]
I've exposed this checkbox for all non-release channels. Getting this in for release channels will come in 16.7-Preview4 pending:
- [ ] LSP platform support inserted: https://devdiv.visualstudio.com/DevDiv/_git/VSLanguageServerClient/pullrequest/253048
- [ ] Roslyn language server shutdown/exit support inserted: https://github.com/dotnet/roslyn/pull/44900

Will track that work here: https://github.com/dotnet/aspnetcore/issues/22522
