### ISSUE TITLE
Improve Blazor/Razor infrastructure performance

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#22717]
We have several issues that have complained about Blazor's typing perf in the current world VS. Given we don't want to invest too heavily into the old world editor we can take a tactical approach to fixing performance issues in the Blazor stratosphere so that they carry over into the new world. For instance, any parser, TagHelper discovery, or project system perf improvements that we apply will not only influence the new world but also the old.

- [x] [Razor.Language assembly not being ngen'd](https://github.com/dotnet/aspnetcore/issues/23314)
- [x] [TagHelper serialization results in huge files with unnecessary data](https://github.com/dotnet/aspnetcore/issues/23174)
- [x] [Editing in large Blazor projects is reallllly slow](https://github.com/dotnet/aspnetcore/issues/22276)
    - This item is a much larger item because there's many reasons as to why editing in a large blazor project is slow.
    - Can work on Matthew Sanders internal project with ease.
- [x] [ProjectWorkspaceState change events fire on every file change.](https://github.com/dotnet/aspnetcore/issues/23169)
- [x] [Divergence checker takes up too much time on the UI thread](https://github.com/dotnet/aspnetcore/issues/22547) - 2 day
- [x] [Accessing feature flags is expensive](https://github.com/dotnet/aspnetcore/issues/21704) - 1 day
- [x] [We need to stop publishing entire generated docs to VS.](https://github.com/dotnet/aspnetcore/issues/21407) - 5 days
- [ ] ~[TagHelper resolution allocates a LOT](https://github.com/dotnet/aspnetcore/issues/23170)~
- [ ] ~[We leak when closing the old world editor](https://github.com/dotnet/aspnetcore/issues/22604) - 5 day~

**Comment by NTaylorMullen** [comment]
Done!

**Comment by boukenka** [comment]
@NTaylorMullen Hello. I am just curious. What do you mean by the terms '_old world editor_' and '_new world_' ? Could you please explain.

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen Hello. I am just curious. What do you mean by the terms '_old world editor_' and '_new world_' ? Could you please explain.

We're in the midst of rehauling our Razor editor to be more performant, faster, and ultimately have more features. So when I refer to "old world editor" i'm referring to the Razor editor that's used today to do any sort of ASP.NET Core development with Razor files. When I say "new world" i'm referring to our rehauling effort.

**Comment by boukenka** [comment]
@NTaylorMullen Thanks for the explanation.
