### ISSUE TITLE
Improve Razor Codespaces reliability infrastructure

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#22722]
- [x] [Add DDRITs integration tests](https://github.com/dotnet/aspnetcore/issues/22720) 4 day
- [ ] ~[Add vendor testing for semantic colorization](https://github.com/dotnet/aspnetcore/issues/21761) - 1 day~
- [x] [Add vendor testing for codespaces](https://github.com/dotnet/aspnetcore/issues/22334) - 2 day
    - [x] Update vendor tests for navigation - .25 days

Total: 7 days

**Comment by ajaybhargavb** [comment]
@NTaylorMullen should this be closed or moved to backlog?

**Comment by NTaylorMullen** [comment]
Close it out!

**Comment by ryanbrandenburg** [comment]
As requested.
