### ISSUE TITLE
Improve language server performance

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#23524]
In our previous milestone we took a stab at improving the performance of cross-cutting concerns which impacted both the old and new Razor editors. In this milestone our goal is to focus on the language server's performance

- [x] [Pre-boot Razor langauge server.](https://github.com/dotnet/aspnetcore/issues/22331) This will ensure users have a snappy first interaction with the editor .5 days
- [x] [Stop substringing the world on parse](https://github.com/dotnet/aspnetcore/issues/23454) 2 days
- [x] [Profile language server allocations/CPU bottlenecks and capture what those are.](https://github.com/dotnet/aspnetcore/issues/23543) We don't necessarily need to fix any bugs from this finding but we do need to understand where things are slowing down. 1 day
- [x] [Profile editing large Razor files](https://github.com/dotnet/aspnetcore/issues/23544). 1 day
- [x] [Profile working in large Razor projects](https://github.com/dotnet/aspnetcore/issues/23546) (have several in mind feel free to reach out). 1 day

Total: 5.5 days

---
Other Items:
- [x] [Newtonsoft.Json deserialization spikes potentially causing OOM in VS.](https://github.com/dotnet/aspnetcore/issues/23597)
- [x] [Project Snapshot Handle Serialization](https://github.com/dotnet/aspnetcore/issues/23945)

**Comment by TanayParikh** [comment]
**Investigations / Bottlenecks / Next Steps:**
- [Investigate System.Text.Json Migration](https://github.com/dotnet/aspnetcore/issues/23966)
