### ISSUE TITLE
Make Razor LSP Editor on-by-default in LiveShare

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#23527]
In 16.8-Preview1 our goal is to make the new editor "on by default". To ensure this goes over well there are a few things we want to ensure happen:

- [ ] [Use the new experimental editor in LiveShare scenarios](https://github.com/dotnet/aspnetcore/issues/23548)
- [x] [Create a guide for reporting an LSP Razor editor issue. This will be what users follow to report an accurate Razor LSP editor issue with enough information for us to diagnose problems](https://github.com/dotnet/aspnetcore/issues/23551). 3 days
- [x] [Investigate adding a configuration option to control LSP editor verbosity](https://github.com/dotnet/aspnetcore/issues/23550) 2 days
- [x] [Allow projects who's project.json's are outside of the scope of the root project](https://github.com/dotnet/aspnetcore/issues/23281) 3 days
- [x] [Failure to shutdown Razor language server leaks.](https://github.com/dotnet/aspnetcore/issues/23831)

## Bug fixes
- [x] [Fix service hub discovery failure](https://github.com/dotnet/aspnetcore/issues/23333) 1 day

Total: 9 days

**Comment by NTaylorMullen** [comment]
We've addressed the majority of these issues, now what's left is updating our LiveShare logic to be able to turn itself on/off in a scoped fashion that works seamlessly with the non-LSP powered editor. Because of that, pushing out to 16.8-Preview2.

**Comment by NTaylorMullen** [comment]
Found lots of issues with swapping the live editor from the old to the new and due to the nature of this change it'd be mostly throw away work. That being said, given the amount of work needed to make this happen we're going to not do this and just wait till we're on-by-default.
