### ISSUE TITLE
Optimize language server performance.

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#24131]
- [x] [TagHelper resolution allocates a LOT](https://github.com/dotnet/aspnetcore/issues/23170) - 3 days
- ~~[ ] [Cache RazorSourceDocument SyntaxTree when Open](https://github.com/dotnet/aspnetcore/issues/24030) 2 days~~
- ~~[ ] [Optimize DefaultRazorProjectEngine.ProcessDesignTime](https://github.com/dotnet/aspnetcore/issues/24081) 2 days - Adjustment Only profile to figure out where we can make improvements.~~
- [x] [SourceTextDiffer `SourceText.ContentEquals(SourceText)` Call is Expensive](https://github.com/dotnet/aspnetcore/issues/24127) 1 day
- [x] [Stop Using Reflection in the LSP Request Invoker](https://github.com/dotnet/aspnetcore/issues/23191)

**Comment by TanayParikh** [comment]
Prioritized other investigations and they revealed `ProcessDesignTime` was not as much of a bottle neck as previously perceived. 

Backlogging:
- [ ] [Cache RazorSourceDocument SyntaxTree when Open](https://github.com/dotnet/aspnetcore/issues/24030) 2 days
- [ ] [Optimize DefaultRazorProjectEngine.ProcessDesignTime](https://github.com/dotnet/aspnetcore/issues/24081) 2 days - Adjustment Only profile to figure out where we can make improvements.
