### ISSUE TITLE
Razor & C# Light bulbs in VS - v0.2

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#24779]
We've done lots of work to enable light bulbs platform agnostically; however, one piece of the light bulb model relies on the ability to provide code actions and then resolve them. This core piece of plumbing is done differently in VSCode and in VS. In VSCode it's done using commands (that's how we implemented it) and in VS there's an expansion of the code action spec. This issue encompasses wiring up the infrastructure to light up our existing Razor light bulbs and enable the first C# light bulb.

- [x] [Add support for Razor's intrinsic light bulbs utilizing the provide/resolve model.](https://github.com/dotnet/aspnetcore/issues/23985)
- [x] [Add support for C#'s "Add using" light bulb.](https://github.com/dotnet/aspnetcore/issues/18173)
- [x] [Add support for C#'s "Fully qualify" light bulb.](https://github.com/dotnet/aspnetcore/issues/24778) - Note we already have this in VSCode but it was implemented platform specific so it'd need to be re-thought to be platform agnostic.

---
- [x] [Disable File Operation Based CodeActions in Liveshare/Codespaces](https://github.com/dotnet/aspnetcore/issues/25128)
- [x] [No Inline C# Diagnostic, Limited Errors](https://github.com/dotnet/aspnetcore/issues/25250)

**Comment by TanayParikh** [comment]
The C# specific lighbulbs are blocked on [No Inline C# Diagnostic, Limited Errors](https://github.com/dotnet/aspnetcore/issues/25250). Currently working on a fix for that. Also, prioritized [Disable File Operation Based CodeActions in Liveshare/Codespaces](https://github.com/dotnet/aspnetcore/issues/25128) as it was a ship blocker. 

Moving this to Preview 4.
