### ISSUE TITLE
Razor LSP: Fix and add tests for known formatting issues

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/aspnetcore#26527]
Below is a list of known issues so far,

- [x] Cleanup doesn't work well in some cases
```razor
@if (true) { <div></div> }
```

- [x] Newline gets added after @: * (https://github.com/dotnet/aspnetcore-tooling/pull/2807)
```razor
    @{
        @:is
    }
```

- [x] `@section` formatting is messed up (https://github.com/dotnet/aspnetcore/issues/27710)

- [x] Formats C# inside tags, (no longer repros)
```razor
<label for="email" @if (true)
                            {<text>a="b"</text>}>c</label>
```

- [x] Html attribute formatting not maintained
```razor
<textarea name="foo"
          id="foo">@("Foo")
        test</textarea>
```

- [x] @if inside @if doesn't work well (https://github.com/dotnet/aspnetcore-tooling/pull/2829)
```razor
@if (true)
{
    @if (true)
    {
        ...
    }
}
```
- [x] OnTypeFormatting sometimes formats more than the expected range (Fixed by 3rd commit in https://github.com/dotnet/aspnetcore-tooling/pull/2585)
- [ ] GenerateConstructor code action fails spectacularly in some cases with `@functions` but not `@code`, (https://github.com/dotnet/aspnetcore/issues/26501) * 5 Days with the primary motivation being to figure out how to track spans after text edits have occurred.
```razor
@code {
    public class Foo { }
}
```

- [ ] NewLines are removed unexpectedly in C# blocks with nested HTML (https://github.com/dotnet/aspnetcore/issues/26836)

- [x] [1041173](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1041173) (Fixed by LSPfication)

- [x] Newline after a nested C# block causes an exception,
```razor
<div>
    <div>
    @if(true)
    {
    }
    
    </div>
</div>
```
- [x] [Multi-line explicit expressions don't format correctly](https://github.com/dotnet/aspnetcore/issues/28326)

- [ ] Multi-line csharp expression indentation at the start of a block (https://github.com/dotnet/aspnetcore/issues/29200)
```razor
@{
    var x = DateTime
            .Now;
}
```

**Comment by ajaybhargavb** [comment]
Only 3 more issues remain from the above list and are tracked separately. Closing this.
