### ISSUE TITLE
Reimplement the Razor compiler using source generators & support incrementality

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#26902]
### Summary

The Razor compiler today represents a significant portion of time experienced by developers in inner-loop scenarios. We should investigate reimplementing it to be based on source generators to avoid the cost of an extra discrete step and removal of another process associated with building.

Today, the Razor compilation process is non-incremental, meaning even the smallest change to any Razor file results in a complete build of all Razor assets in a project. We should investigate the potential for adding further incrementality to Razor compilation so that unnecessary compilation time is not spent between edits.

### Notes
The hypothesis is that an additional compile step can be eliminated along with state management if we are able to use source generators. We might also benefit of not producing janky types in design time builds.

## Tasks

* [x] Draft PR: https://github.com/dotnet/aspnetcore/pull/28807
* [x] SDK PR PR: https://github.com/dotnet/sdk/pull/15756
* [x] Combine views and app assembly: https://github.com/dotnet/aspnetcore/issues/29862
* [x] Add tests for SourceGenerators
  * [x] Migrate tests for SG-specific SourceDocuments from Razor.Language
  * [ ] Add integration tests for SG-specific scenarios
* [ ] Tooling EnC support for source generated files: https://github.com/dotnet/roslyn/issues/50039 (ETA 2/8)
* [ ] Tooling EnC support for swapping between Razor design time and source generated files: ETA 2/15. No tracking issue.
* [ ] Compiler: Framework to support incrementalism in source generators: No tracking issue, but this is not blocking (https://github.com/dotnet/roslyn/issues/51257)

**Comment by stefanloerwald** [comment]
Speaking as someone who implemented a few source generators for Blazor, I absolutely love that this is one of the things potentially coming in net6.0!

However, please make sure that SGs should also support some sort of sequencing by that time. Otherwise all current SGs which rely on evaluating any of the generated code (the .g.cs files, e.g. for analyzing parameters) would break.

Thanks!

**Comment by pranavkm** [comment]
@captainsafia let's use the smaller line items to track further work. We'll consider this issue resolved for preview4. 

@stefanloerwald we made the Roslyn folks aware of your requirement. In addition, there are some ordering requirements for some of the in-box source generators e.g. System.Text.Json's source generator needs to run after the Razor one, so we have vested interest in seeing it addressed.
