### ISSUE TITLE
[Epic] ASP.NET Performance goals for .NET 6.0

### ISSUE THREAD

**Issue by sebastienros** [dotnet/aspnetcore#27226]
This is a high-level tracking work item for ASP.NET performance work during the .NET 6.0 time frame.

Even though there are many other areas that could be investigated, this list contains the top priority items that are currently considered for dedicated performance work.

- [ ] https://github.com/dotnet/aspnetcore/issues/27221 HTTP APIs in MVC
- [ ] https://github.com/dotnet/aspnetcore/issues/27220 Authentication middleware
- [ ] https://github.com/dotnet/aspnetcore/issues/27223 GRPC
- [ ] https://github.com/dotnet/runtime/issues/48619 Logging
- [x] https://github.com/dotnet/runtime/issues/46970 Caching improvements
- [ ] https://github.com/dotnet/runtime/issues/47239 Caching expiration

~~https://github.com/dotnet/aspnetcore/issues/27222 TLS~~ (sub-item for yarp)
~~https://github.com/dotnet/aspnetcore/issues/27225 Yarp~~ (moved to yarp)
~~https://github.com/dotnet/aspnetcore/issues/27385 Razor Pages~~ (de-prioritized)

**Comment by danmosemsft** [comment]
Added ASP.NET to the title to disambiguate the tracking page a bit.

**Comment by danmosemsft** [comment]
@sebastienros it seems there's no work identified on the Libraries team here, is that right? But possibly some may emerge as you investigate?

**Comment by sebastienros** [comment]
@danmosemsft exactly. We'll first establish baselines to understand where the gains can be done, and we'll eventually find some potential improvements to make in the runtime. Though based on our current understanding most work should be within this repos.

**Comment by davidfowl** [comment]
@danmosemsft The obvious ones:
- TLS
- Logging
- Auth (Crypto)

I'm sure there'll be more.

**Comment by danmosemsft** [comment]
How will you be setting goals @sebastienros ? We should set goals rather than do open ended perf work, because the latter is hard to prioritize. I realize investigation might inform the goals.

**Comment by sebastienros** [comment]
We haven't defined any specific goals, these are just domains we know need to get some work done since we haven't looked at them as much as the TE oriented scenarios. For TLS, one concrete goal would be a compete one, and there are a few options for this one, either by targeting nodejs perf on a web app, or nginx with yarp.

**Comment by SteveVaneeckhout** [comment]
What about [System.Text.Formatting](https://github.com/dotnet/corefxlab/)? According to the README:
> ... these APIs are optimized for creating text for the Web. They do formatting with minimum GC heap allocations and can format directly to UTF8 streams. This can result in significant performance wins for software that does a lot of text formatting for the Web, e.g. generating HTML, JSON, XML.

The code hasn't been touched since 2018. Is it still relevant?

**Comment by Pilchie** [comment]
Tagging @jeffhandley  and @adamsitnik here, as I just linked dotnet/runtime#46970 and dotnet/runtime#47239 here so we don't forget about them.

**Comment by soroshsabz** [comment]
ITNOA

Is there any plan for .NET 8?

**Comment by davidfowl** [comment]
@soroshsabz What is that?

**Comment by soroshsabz** [comment]
@davidfowl I say is there any plan to meet performance goals for .NET 6.0 in .NET 8.0?

**Comment by mairaw** [comment]
Can this .NET 6 epic be closed? If there's any remaining work, should you have a new one created? I'm trying to clean up the .NET 6 project.

**Comment by danroth27** [comment]
Closing as all sub issues are separately tracked.
