### ISSUE TITLE
[Epic] API doc improvements for .NET 6

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#27285]
* [ ] Add namespace summaries to ASP.NET Core API docs
* [ ] API docs with 1000+ views: Improve IntelliSense docs and link to relevant conceptual docs and/or add code samples.
* [ ] API docs with 500+ views: Improve IntelliSense docs
* [ ] API docs used from templates: Improve IntelliSense docs

TODO: Create and link to child issues.

**Comment by dougbu** [comment]
Including this in the DoI project for discussion in that context

**Comment by adityamandaleeka** [comment]
We should have the data for views now. Need to go through and review/improve the docs.
