### ISSUE TITLE
[Epic] Build infrastructure improvements

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#27609]
This issue collects all the individual issues for improvements that we want to do moving forward to our infrastructure.

### Repo dev and contributor experience
- [ ] VS Code and VS 4 Mac experience. https://github.com/dotnet/aspnetcore/issues/27260
- [ ]  Updating public API files outside of Visual Studio. https://github.com/dotnet/aspnetcore/issues/27605

### Complete Helix migration
- [ ] Run hosting functional tests on Helix. https://github.com/dotnet/aspnetcore/issues/8247
- [ ] Run Components end to end tests on Helix. https://github.com/dotnet/aspnetcore/issues/6857

### Codebase quality improvements
- [ ] Enable more code analyzers for the product. https://github.com/dotnet/aspnetcore/issues/24055
  * The person working on this will drive the effort, which consists of choosing an initial set of analyzers to enable.

### Testing reliability reporting tool
- [ ] Bring back what's broken in some shape or form. https://github.com/dotnet/aspnetcore/issues/27606

### Performance readiness
- [ ] Ensure our microbenchmarks can run. https://github.com/dotnet/aspnetcore/issues/27607

### Infrastructure code duplication removal
- [ ] Unify test/publish for helix/local scenarios https://github.com/dotnet/aspnetcore/issues/27296

**Comment by dougbu** [comment]
Including this in the DoI project for discussion in that context

**Comment by mkArtakMSFT** [comment]
Assigned this to `6.0` as we will plan to tackle individual items on this list throughout the preview releases.
