### ISSUE TITLE
Blazor specific libraries size-reduction tracking

### ISSUE THREAD

**Issue by samsp-msft** [dotnet/aspnetcore#27668]
Source generators can be used to convert code that does reflection.emit at runtime to source generators which will create code at build time rather than runtime. The generated code can then be analyzed by the illinker or native AOT enabling those scenarios. Blazor doesn't use Reflection.Emit directly (though it may use it via dependency injection libraries). However Blazor does use reflection extensively, in the following areas:

 * [ ] Routing (Router.cs, RouteTableFactory.cs), to walk the set of exported assembly types to find those with RouteAttribute
 * [ ] Component factory (ComponentFactory.cs), to discover the properties with InjectAttribute, which we later populate via DI
 * [ ] Parameter assigmment (ComponentProperties.cs, MemberAssignment.cs, CascadingParameterState.cs, PropertySetter.cs), to find the properties on a type with ParameterAttribute and to write supplied values to them #29550
 * [ ] Layouts (LayoutView.cs, RouteView.cs), to discover the LayoutAttribute on a component
 * [ ] Data binding (InputBase.cs), because components declare their bound ValueExpression as an Expression<Func<TValue>> so that the validation system can match it to a FieldIdentifier
 * [ ] Validation (FieldIdentifier.cs, EditContextDataAnnotationsExtensions.cs), to know  to convert lambda expressions to FieldIdentifier instances (type+propertyname pairs), and to read values of properties matching FieldIdentifier entries in the EditContext, so it can pass those values to DataAnnotations for validation
 * [x] WebAssembly startup (EntrypointInvoker.cs), to find and invoke the assembly entrypoint method #30600 
 * [ ] Lazy loading (LazyAssemblyLoader.cs), to load assemblies dynamically via Assembly.Load(filenameString)
 * [ ] WebAssembly auth (WebAssemblyAuthenticationServiceCollectionExtensions.cs), to generate an "inferred client ID" via Assembly.GetCallingAssembly().GetName().Name
 * [ ] `<component>` tag helper (RootComponentTypeCache.cs, ComponentParametersTypeCache.cs), to look up the type instances corresponding to serialized descriptors of components being rendered into HTML markers
 * [ ] BlazorPack (SequenceOfT.cs), to check whether a type is a value type via typeof(T).GetTypeInfo().IsValueType

**Comment by danmosemsft** [comment]
Transferring to asp.net repo - I believe this is essentially all ASP.NET owned? There is a separate story for DI.

cc @mkArtakMSFT  - this shows up in https://themesof.net/?q=is:open%20kinds:teui under WASM.

 cc @marek-safar

**Comment by danmosemsft** [comment]
making title a bit more specific to improve the tree view.

**Comment by charlesroddie** [comment]
Can this be structured so that the core of blazor doesn't depend on reflection/source generators? Source generators are C#-only, and using annotations and DI as an essential part of runtime behaviour is also a C# preference. So these can go together as C# blazor tooling, and F# and the rest of dotnet can develop Blazor apps without using reflection/DI/annotations.

**Comment by mkArtakMSFT** [comment]
Marked this as `cut`. We may do some of these items, but can't commit.
