### ISSUE TITLE
Improvements to web api experience around OpenAPI and API Explorer

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#27889]
An umbrella issue to track Swagger / OpenAPI work:

* [x] https://github.com/dotnet/aspnetcore/issues/27591
* [ ] Enable OpenAPI analyzer by default in API apps
* [ ] Bugs / improvements:
     * [x] [Media type application/problem+json lost in combination with ProducesAttribute](https://github.com/dotnet/aspnetcore/issues/19510)
     * [x] [ProducesResponseType(typeof(void), ...) causes ApiExplorer to indicate the return type is ProblemDetails](https://github.com/dotnet/aspnetcore/issues/7874)
    * [ ] [Identify if any additional work is pending in ProblemDetails is not returned for 404NotFound and 500Exception](https://github.com/dotnet/aspnetcore/issues/4953)
   * [ ] [Api.Analyzers not recognizing methods from a Base Class](https://github.com/dotnet/aspnetcore/issues/4410)
   * [ ] [Create and include an analyzer that validates action method return types match the declared ActionResult<T>](https://github.com/dotnet/aspnetcore/issues/8535)
   * [ ] [API analyzers should support undeclared 200 status codes](https://github.com/dotnet/aspnetcore/issues/15385)
   * ~~[ ] [Discriminated unions](https://github.com/dotnet/aspnetcore/issues/27890)~~

**Comment by jeremyVignelles** [comment]
Would #28060 fit here ?

**Comment by dodyg** [comment]
Will ApiExplorer support all the endpoints created via Houdini?

**Comment by Youssef1313** [comment]
Mvc.OpenApi.Analyzers was dropped. See https://github.com/dotnet/aspnetcore/issues/68087

I don't see any remaining work that needs to happen here. So closing as completed.
