### ISSUE TITLE
Default Blazor Wasm template managed libraries size reduction

### ISSUE THREAD

**Issue by marek-safar** [dotnet/aspnetcore#30098]
There is a lot of unnecessary assemblies left in the default Blazor Wasm template after trimming.

### The list of assemblies which should be easy to fully eliminate

- [ ] System.Collections.Concurrent.dll - *It has no use in single threaded environment*
- [x] System.Collections.Immutable.dll - *It does not seem to be needed at all* https://github.com/dotnet/runtime/pull/53317
- [ ] System.ComponentModel.dll - *Single interface method is used from it*
- [x] System.Console.dll - #31148
- [x] System.IO.Pipelines #27782
- [ ] System.Linq.dll - *It should be possible to remove most if not all use of it*
- [x] System.ObjectModel.dll - #31460
- [ ] System.Private.Uri.dll - *Only System.Uri::.ctor(string) is needed*
- [ ] System.Runtime.CompilerServices.Unsafe.dll https://github.com/dotnet/runtime/issues/45475
- [ ] System.Text.Encodings.Web.dll - *Single use to create JsonEncodedText from hardcoded string constant*
- [ ] Microsoft.Extensions.Logging.Abstractions.dll #27721
- [ ] Microsoft.Extensions.Logging.dll #27721

Cleaning this up could reduce the trimmed output for managed libraries for the default template by ~15%

@eerhardt @lewing @SamMonoRT

**Comment by javiercn** [comment]
@marek-safar thanks for doing this investigation.

There are indeed some low-hanging fruits here.

For the logging assemblies, is the linker smart enough to remove the callsites from other assemblies if we tell it to remove the entire library?

**Comment by marek-safar** [comment]
Yes, if you remove the need for the dependency the linker will update the code not to require the assembly at all.

**Comment by eerhardt** [comment]
>  System.Collections.Concurrent.dll - It has no use in single threaded environment
 System.Collections.Immutable.dll - It does not seem to be needed at all

I believe these are being rooted by System.Text.Json, and will be removed with the source generator work. (With the exception of `ConcurrentDictionary`, since ASP.NET and Microsoft.Extensions reference it in many places.)

cc @tannergooding - who is working on enabling the STJ source generator for Blazor WASM.

>  System.ComponentModel.dll - Single interface method is used from it

But that single interface is pretty important - `IServiceProvider`. You can't do DependencyInjection without it.

**Comment by eerhardt** [comment]
>  System.Text.Encodings.Web.dll - Single use to create JsonEncodedText from hardcoded string constant

I'm not understanding this comment. I see this assembly used to do escaping of property names and strings in System.Text.Json:

For example: 

* https://github.com/dotnet/runtime/blob/8a52f1e948b6f22f418817ec1068f07b8dae2aa5/src/libraries/System.Text.Json/src/System/Text/Json/Writer/JsonWriterHelper.Escaping.cs#L56-L59
* https://github.com/dotnet/runtime/blob/8a52f1e948b6f22f418817ec1068f07b8dae2aa5/src/libraries/System.Text.Json/src/System/Text/Json/Writer/JsonWriterHelper.Escaping.cs#L138-L142

**Comment by marek-safar** [comment]
> System.Collections.Concurrent

This is primary Blazor report. This type is used at several places with no good reason for WebAssembly.

> But that single interface is pretty important - IServiceProvider. You can't do DependencyInjection without it.

Do we need to do dependency injection in the default template? If it's really that important should we have an assembly with a single used method?

> I'm not understanding this comment. I see this assembly used to do escaping of property names and strings in System.Text.Json:

This is primary Blazor size report. I didn't want to mix it with problems in STJ and will probably file a separate issue about it.

**Comment by mkArtakMSFT** [comment]
@marek-safar should this be closed or moved to the `dotnet/runtime` repo?

**Comment by mkArtakMSFT** [comment]
Talked to @marek-safar offline. Closing as there is no pending work left here.
