### ISSUE TITLE
MapAction umbrella issue

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#30276]
* [ ] Implement minimal version (https://github.com/dotnet/aspnetcore/issues/29684)
* [ ] Add benchmarks (https://github.com/dotnet/aspnetcore/issues/29915)
* [ ] MVC feature parity
  * [ ] Map action filter
  * [ ] Validation
  * [ ] Make as many IActionResult instances work with MapAction
  * [ ] API Explorer

**Comment by pranavkm** [comment]
@halter73 could you add other items from your document to this? Also could you file issues to start tracking individual items?

**Comment by mkArtakMSFT** [comment]
@pranavkm isn't this the same as https://github.com/dotnet/aspnetcore/issues/27347 ?

**Comment by pranavkm** [comment]
Sure. Can we make sure we track individual feature work as part of that issue? Thanks!
