### ISSUE TITLE
HttpLogging Middleware

### ISSUE THREAD

**Issue by jkotalik** [dotnet/aspnetcore#31863]
- [X] https://github.com/dotnet/aspnetcore/issues/31843
- [ ] https://github.com/dotnet/aspnetcore/issues/31844
- [ ] https://github.com/dotnet/aspnetcore/issues/31849
- [X] https://github.com/dotnet/aspnetcore/issues/31859
- [ ] https://github.com/dotnet/aspnetcore/issues/39200

**Comment by adityamandaleeka** [comment]
Closing this epic since it's just tracking other issues at this point.
