### ISSUE TITLE
Epic: Minimal hosting and actions

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#32378]
# Vision

```C#
#!/usr/bin/env dotnet run

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddSqlite<Todo>(builder.Configuration["connectionString"] ?? "Data Source=todos.db");

var app = builder.Build();

// ...

// Step 5: Input validation
app.MapPost("/todos", async (Validated<Todo> inputTodo, TodoDb db) =>
{
    var (todo, isValid) = inputTodo;
    if (!isValid) return Problem(inputTodo);

    db.Todos.Add(todo);
    await Todos.SaveChangesAsync();

    return CreatedAt(routes.GetTodo.Url(todo.Id), todo);
};

app.Run();

// ...
```

From: #30580 User learning arc for new minimal/focused ASP.NET Core API experience

# Minimal Action Feature Work

- [x] #29684 Implement a minimal version of MapAction
- [x] #29915 Add benchmarks for MapAction
- [x] #30448 Add new "MapAction" overloads
- [x] #31181 Add API to turn delegate or MethodInfo into a RequestDelegate
- [x] #30662 Add OpenAPI/Swagger support to minimal actions
- [x] #33729 Create IResult-returning static methods
- [x] #32565 Add IResult implementations for more IActionResults
- [x] #30322 RequestDelegateFactory should produce clear errors for invalid Delegates
- [x] #32377 Use CultureInfo.InvariantCulture when TryParsing minimal action parameters
- [x] ~#33687 Add easier way to name endpoints for easier link generation~ Cut
- [x] #32375 Use nullibility to infer optionality of service and body parameters
- [x] ~#32376 Infer collection interfaces like IList come from the body in minimal actions~ Cut
- ~#30666 Design validation for minimal actions~ (cut for .NET 6)
- ~#32563 Use InferFromServicesAttribute to infer non-interface parameters in minimal actions come from services~ Replaced by https://github.com/dotnet/aspnetcore/pull/32737
- ~#30668 Enable customization of input and output formatting for minimal actions (out of scope?)~
- ~#30670 Add linker-friendly Roslyn source gen version of RequestDelegateFactory~

# Minimal Hosting Feature Work

- [x] #30354 "Minimal hosting" for ASP.NET Core applications
- [x] #31861 ResolveServiceProviderFactory should work with Minimal Hosting
- [x] https://github.com/dotnet/aspnetcore/pull/33462 Make WebApplicationFactory work with top level statements (without CreateHostBuilder entry point)
- [x] #32451 Add default global usings to Microsoft.NET.Sdk.Web
- [x] ~#32124 Add better certificate configuration support to WebApplication~ Cut

# Minimal Hosting Bugs

- [x] #32415 Web root is incorrect when using the minimal host
- [x] #32383 Minimal host does not read environment specific configuration
- [x] #32432 [Perf] WebApplication.CreateBuilder potentially inefficient, results in many file system checks
- [x] #33082 Use a ChainedConfigurationSource to share sources between WebApplicationBuilder and inner host
- [x] #33083 Remove Configuration.AutoUpdate

# Project Templates
- [x] #30665 Add empty template for Minimal Scenarios 
- [x] https://github.com/dotnet/aspnetcore/pull/33393 Remove cast from empty template
- [x] #33813 Remove `<LangVersion>Preview</LangVersion>` from empty web template
- [x] #33944
- [x] #34123
- [x] #32471 Update blazorwasm-hosted templates to use minimal host

# Docs

- [x] #31992 Add getting started docs for minimal hosting

**Comment by terrajobst** [comment]
Seems like this should be parented under https://github.com/dotnet/aspnetcore/issues/27883?

**Comment by rafikiassumani-msft** [comment]
Closing this epic as I moved the remaining issues to .NET7 planning milestone.
