### ISSUE TITLE
Semantic tokens experience improvements aka "Project Palette"

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#33200]
We've identified that the experience of using Semantic Tokens (specifically in larger applications) is sub-optimal. This issue tracks improving the experience overall, with a specific eye to performance

- [x] https://github.com/dotnet/aspnetcore/issues/33199 - Don't wait for C# tokens
- [x] https://github.com/dotnet/aspnetcore/issues/31416 - Tracks how slowness in TextMate prevents SemanticTokens from advancing as early as they could.
- [x] https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1336412 - Causes a "bug farm" of incorrect colorization.
    1. https://github.com/dotnet/aspnetcore/issues/27447
- [x] https://github.com/dotnet/aspnetcore/issues/33001 - project.razor.json gets over-ridden due to incomplete project knowledge, which leads to "flashing" colors.
- [x] https://github.com/dotnet/aspnetcore/issues/33567 - Unknown coloration issue in a common case.
- [x] Needs to be fast
    - [x] Fast for Editing
    - [x] Fast on startup

**Comment by ryanbrandenburg** [comment]
@mikadumont and @danroth27 what's your idea of how fast this should end up being? My understanding from my limited knowledge of UX is that things that happen in <200ms are generally perceived as "instant". Certainly "instantly" would be a nice goal, but y'all have better ideas of what users expect and desire.

**Comment by ryanbrandenburg** [comment]
The remaining items here reflect external issues, but they still need to be tracked.

**Comment by ryanbrandenburg** [comment]
I ran some un-scientific tests on LSP VS Legacy on Large apps. And found that LSP was slightly faster to fully color a file on startup than legacy for one of the large apps we test with:
|Type|Seconds|
|-|-|
|LSP|15.9|
|LSP|13.5|
|Legacy|19.8|
|Legacy|18.15|

For editing, both are too fast to get reliable stopwatch timing, but they feel roughly equivalent.

**Comment by ryanbrandenburg** [comment]
Editing certainly feels faster than it used to, but there is still a noticeable (.5s?) delay between pasting a Component and it getting Semantic colors.

**Comment by ryanbrandenburg** [comment]
I'm pretty sure we've identified the problem. When we make an edit we send `textDocument/didChange` to the client, causing VS to immediately trigger `textDocument\semanticTokens\edits`. The problem is, at that point C# hasn't propagated the new version and returns us the HostDocumentSyncVersion from the previous version. When the Razor and C# versions don't match we return `null` because otherwise we'd either cause any C# tokens to "flash" due to missing C# info or possibly mis-color if anything has moved. VSLanguageServerClient then puts us on a bit of a timer before trying again because we obviously have stuff to work out, and then by the time they've asked again everyone is caught up and we colorize.

This explains the behavior I was seeing where (other than a few initial `textDocument/semanticTokens` request) our total request time was actually very short (<50ms), but the time it takes for colors to show up is quite large(~.5 seconds).

Not sure what the fix is yet, but very excited to have a path of attack.

**Comment by ryanbrandenburg** [comment]
Old code:
![OldAndBusted](https://user-images.githubusercontent.com/14987221/126009514-36463480-4bc6-47c4-8a9c-3cc06d18a560.gif)
With TrySynchronizeVirtualDocumentAsync:
![NewAndSpeedySemantic](https://user-images.githubusercontent.com/14987221/126009553-ffbe4abe-0cd2-4814-8c6d-b290aafc0b75.gif)

**Comment by ryanbrandenburg** [comment]
Looking at the startup speed it looks like that may be independent of anything Razor does, and just be related to general project load items. Will need to give this another look and probably confirm by comparing to Roslyn.

**Comment by ryanbrandenburg** [comment]
We've seen some massive improvements in startup perf (likely due to contributions on the platform side which prevented some Language Servers from being launched unless they were needed). The following was generated on a very large app.

|Point of test|Time (in seconds)|
|-|-|
|With RangeRequest|60-120|
|Without RangeRequest|~35|
|Preview 4|18|
|After Platform improvements|8|

Given that I'm going to call `Fast on startup` complete, thus completing this item. #31416 will stay open because it's a tracking issue for the VS-side item, but I feel we've gotten enough out of it to call the user experience here "good" until we hear otherwise.
