### ISSUE TITLE
Hot Reload application changes during development inner-loop from the .NET CLI

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspnetcore#33826]
This epic covers all scenarios relating to supporting Hot Reload and associated experiences (including auto-build, auto-restart, etc.) from the .NET CLI in .NET 6.

### User Stories & Issues
 - [x] [`dotnet watch run` supports applying code changes to a running app via Hot Reload](https://github.com/dotnet/sdk/issues/15849)
 - [x] [`dotnet watch run` is configurable with regards to its behavior when source changes are detected](https://github.com/dotnet/sdk/issues/15851)
 - [x] [`dotnet watch run` applies project-type-specific defaults for its behavior when source changes are detected](https://github.com/dotnet/sdk/issues/15857)
 - [ ] ~`dotnet run --watch` is an alias for/equivalent to `dotnet watch run`~
 - [x] `dotnet watch run` behavior can be interactively controlled from the command line while it is active

**Comment by DamianEdwards** [comment]
We've done as much here feature-wise in .NET 6 as we expect to. We can open specific issues from now on for any changes.
