### ISSUE TITLE
[Epic]: Minimal APIs enhancements

### ISSUE THREAD

**Issue by rafikiassumani-msft** [dotnet/aspnetcore#39327]
This epic is to track all the potential work for Minimal APIs for .NET7. 

### Parameter Binding
- [x] Minimal APIs route grouping :  #36007 
- [x] `Stream/PipeReader` parameter binding: #38153
- [x] `StringValues` parameter binding: #36726
~~[ ] API to invoke binding logic in `RequestDelegateFactory` : #38003~~
- [x] Binding to Uri type : #36649
~~[ ] `FromHeaderAttribute` and `FromQueryAttribute` enhancement: #36418~~
~~[ ] More Parameter binding extensibility: #35489~~
- [x] Array support for `QueryString` binding: #32516
~~[ ] Fix type mismatches between parameter and route constraints: #36859~~
~~[ ] #39430~~
- [x] File parameter binding

### Minimal hosting
~~[ ] Allow minimal host to be created without default HostBuilder: #32485~~

### Result Enhancements
- [x] Improve testability for `IResult` methods: #37502
- [x] Clean up logs for `IResult` method : #36666 
~~[ ] Extensible Result processing, e.g. delayed execution, shortcutting~~
~~[ ] #39431~~

### Endpoint Filters
- [x] Support Minimal endpoint filters: #37853

### Configurations
- [x] Provide a better API for `JsonOptions` configurations: #39226 
- [x] Make `IConfigureOptions` consistent: #39251 

### Validation
~~[ ] Add Support for validation framework for Minimal actions: #30666~~

### OpenAPI Improvements
- [x] Enhancements for OpenApi: #37098 

### Developer Experience
- [x] Support more `ProblemDetails` (DeveloperExceptionPage, Middleware/ExceptionHandler, etc.)
- [x] Support `ProblemDetails` Titles: #36417
~~More Minimal APIs Analyzers: #36637~~
~~[ ] #44821~~
~~[ ] #44822~~
~~[ ] Improve error messages for optional parameters and `TryParse` failures: #35501~~

### Expand Minimalistic Philosophy
- [x] Simplify Authentication and Authorization configs for Minimal APIs: #34545
- [x] Add antiforgery support for Minimal endpoints: #38630
~~[ ] #44823~~
- [x] #39429
