### ISSUE TITLE
[Theme] Add support for migrating .NET Framework apps to .NET Core

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#40078]
This issue tracks several related items involved in our ongoing effort to help migrate .NET Framework apps to .NET Core. 

## Details
_TBD_

## Issues

* [ ] Add missing documentation for integrating Owin-based apps with ASP.NET Core https://github.com/dotnet/aspnetcore/issues/39943
* [ ] VS tooling to support YARP based migration _insert AzDo issue here_
* [ ] Produce adapters for System.Web.HttpContext #40001 
* [ ] Identify way to share session state with "backend" System.Web app - https://github.com/dotnet/aspnetcore/issues/40079
* [ ] Support sharing auth state with "backend" System.Web app - https://github.com/dotnet/aspnetcore/issues/40083

**Comment by alexthekid07** [comment]
Can you guys confirm VB is effectively abandoned for newer .NET?
There's not really any viable roadmap I've seen to migrate from .NET 4.8 in VB to .NET 5/6/7 in VB... so the only real option is a complete and total rewrite from scratch.

**Comment by KathleenDollard** [comment]
We have _not_ abandoned VB in newer versions of .NET.

Before .NET Core, ASP.NET stopped supporting VB except for WebAPI (there is no Razor engine). If you are writing web apps there are ways to work around this. Overall the experience of changing to newer .NET is about the same for a C# or VB project. 

If you have a more specific issue or concern, VS Feedback is one venue you can use for a more focused discussion.

**Comment by slang25** [comment]
Is an approach like [IISCrossover](https://github.com/davidfowl/IISCrossover) being considered in scope for this theme? I think this would really help unblock many teams.

**Comment by pranavkm** [comment]
@slang25 we are working on a solution using YARP instead. We'd initially considered IISCrossover, but realized that outside of a few limited scenarios we need to solve the same problems with it that we also run in to with YARP. Given YARP is production-ready, we decided to base our solution on it.

**Comment by VenkateshSrini** [comment]
Is there a tool that you are planning to do this migration or is this going to be only documentation updates

**Comment by twsouthwick** [comment]
@VenkateshSrini There's some VS tooling to enable the YARP integration as well as some runtime changes being explored. The list  in the first comment contains the areas being explored currently as part of this theme. For more details on them, you can click on the associated link.

**Comment by gumbarros** [comment]
> Can you guys confirm VB is effectively abandoned for newer .NET? There's not really any viable roadmap I've seen to migrate from .NET 4.8 in VB to .NET 5/6/7 in VB... so the only real option is a complete and total rewrite from scratch.

You can use this extension to convert your VB code to C# and then convert it to .NET Core:
https://marketplace.visualstudio.com/items?itemName=SharpDevelopTeam.CodeConverter

**Comment by adityamandaleeka** [comment]
Update: we've just released a preview of this work, with more to come. Here's a blog post with more information (including a video of a BUILD talk about it): https://devblogs.microsoft.com/dotnet/incremental-asp-net-to-asp-net-core-migration/

The work is being done in https://github.com/dotnet/systemweb-adapters so please file your issues/requests about it there. I'll close this issue now.
