### ISSUE TITLE
OutputCaching Middleware

### ISSUE THREAD

**Issue by sebastienros** [dotnet/aspnetcore#40232]
- [x] https://github.com/dotnet/aspnetcore/issues/40221
- [x] https://github.com/dotnet/aspnetcore/issues/40222
- [x] https://github.com/dotnet/aspnetcore/issues/40223
- [x] https://github.com/dotnet/aspnetcore/issues/40224
- [ ] https://github.com/dotnet/aspnetcore/issues/40225
- [x] https://github.com/dotnet/aspnetcore/issues/40226
- [x] https://github.com/dotnet/aspnetcore/issues/40227
- [ ] https://github.com/dotnet/aspnetcore/issues/40228
- [ ] https://github.com/dotnet/aspnetcore/issues/40229
- [ ] https://github.com/dotnet/aspnetcore/issues/40230
- [ ] https://github.com/dotnet/aspnetcore/issues/40231

**Comment by adityamandaleeka** [comment]
Closing this epic. The bulk of this was done in 7.0 and there are issues open for other work we can consider in the future.
