### ISSUE TITLE
[Epic] Route Groups

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#41433]
Now that the initial implementation of `MapGroup` has been merged, I'm closing the initial route grouping issue at #36007 and am using this "Epic" issue to track the remaining work for .NET 7.

- [x] [[Route Groups] Support AddFilter, WithOpenApi and other additive conventions #41427](https://github.com/dotnet/aspnetcore/issues/41427)
- [x] [[Route Groups] WithTags et al. should target IEndpointConventionBuilder #41428](https://github.com/dotnet/aspnetcore/issues/41428)
~~[ ] [[Route Groups] Add default metadata to endpoints exposing group structure #41429](https://github.com/dotnet/aspnetcore/issues/41429)~~
~~[ ] [[Route Groups] Investigate link generation bug #41430](https://github.com/dotnet/aspnetcore/issues/41430)~~
~~[ ] [[Route Groups] Implement IApplicationBuilder to support grouped middleware #41431](https://github.com/dotnet/aspnetcore/issues/41431)~~
~~[ ] [[Route Groups] Investigate callback based API #41432](https://github.com/dotnet/aspnetcore/issues/41432)~~
- [x] [[Route Groups]  Rename GroupRouteBuilder to RouteGroupBuilder #41781](https://github.com/dotnet/aspnetcore/issues/41781)

**Comment by rafikiassumani-msft** [comment]
Closing the issue. Will move the remaining items to .NET8 Planning.
