### ISSUE TITLE
[AOT] Meta issue for warnings from outside of aspnetcore

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#45911]
Publishing an empty aspnetcore app results in warnings from non-aspnetcore code. This issue is to ensure they are tracked, and we have contacted the right people to fix those warnings before release.

- [x] Warnings from System.Linq.Expressions because project is not annotated https://github.com/dotnet/runtime/issues/75480
- [x] Warnings from Microsoft.Extensions.Logging related to DI configuration. Bug in the NativeAOT compiler https://github.com/dotnet/runtime/issues/75898
- [x] Warnings from Microsoft.Extensions.DependencyInjection. The solution is to remove `RequiresDynamicCode` from APIs. Warnings are currently suppressed https://github.com/dotnet/runtime/pull/79425
- [x] Warnings from Microsoft.Extensions.DependencyInjection related to GetGenericType. Bug in the NativeAOT compiler https://github.com/dotnet/runtime/issues/81129

**Comment by eerhardt** [comment]
Closing as we no longer need to track this. `dotnet new api -aot` is now able to be published successfully with no warnings.
