### ISSUE TITLE
[EPIC] `dotnet user-jwts` in .NET 8

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#46263]
This epic aggregates the collection of bug fixes and enhancements that we hope to ship in the `dotnet user-jwts` tool for .NET 8..

- [x] https://github.com/dotnet/aspnetcore/issues/46218
- [x] https://github.com/dotnet/aspnetcore/issues/44869
- [x] https://github.com/dotnet/aspnetcore/issues/45141
- [ ] https://github.com/dotnet/aspnetcore/issues/41872

**Comment by glen-84** [comment]
@captainsafia When will the fixes in #48385 be backported to .NET 7?

**Comment by captainsafia** [comment]
@glen-84 We can backport things given a certain amount of interest in getting the fix out. Is this blocking a key feature for you?

**Comment by glen-84** [comment]
Not really, just an annoyance.

**Comment by captainsafia** [comment]
@glen-84 I can see about taking this for the next servicing release. Given there is no workaround, it does [meet the servicing bar](https://github.com/dotnet/aspnetcore/blob/main/docs/Servicing.md#servicing-bar).

**Comment by captainsafia** [comment]
> This still seems to be broken:
> 
> ```shell
> $ dotnet --version
> 8.0.100-rc.2.23502.2
> $ dotnet user-jwts list --project src/Api/
> The project file 'src/Api/src/Api/' does not exist.
> ```

Argh -- I see the issue. Resolved in https://github.com/dotnet/aspnetcore/pull/51762.

**Comment by captainsafia** [comment]
Yep -- let's go ahead and do that.
