### ISSUE TITLE
Auth improvements in ASP.NET Core 8

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#47286]
To improve the auth experience for self-hosted Single Page Apps (SPA) in ASP.NET Core 8, we will:

1. Extend cookie-based authentication with endpoints that SPA apps can use to customize the identity management experience (without relying on server-rendered UI).
2. Enhance ASP.NET Core Identity to support token-based auth
3. Remove Duende from the templates and use built-in ASP.NET Identity for the "Individual Accounts" option.

More details to follow.

See:

- [x] https://github.com/dotnet/aspnetcore/issues/47288
- [x] https://github.com/dotnet/aspnetcore/issues/48786
- [x] https://github.com/dotnet/aspnetcore/issues/47226

related: https://github.com/dotnet/aspnetcore/issues/42158

**Comment by cyclr-adrian** [comment]
> 2. Enhance [ASP.NET](http://asp.net/) Core Identity to support token-based auth

Will this include the ability for [ASP.NET](http://asp.net/) Core to generate tokens based on a `client_id` and `client_secret` with client credential OAuth2 flow?

**Comment by mkArtakMSFT** [comment]
> Will this include the ability for [ASP.NET](http://asp.net/) Core to generate tokens based on a client_id and client_secret with client credential OAuth2 flow?

No.

**Comment by davidfowl** [comment]
See https://devblogs.microsoft.com/dotnet/improvements-auth-identity-aspnetcore-8/
