### ISSUE TITLE
[Tracking] Parser improvements feedback

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/aspnetcore#5093]
I'm putting all the miscellaneous improvements we want to do after we get the end-to-end working in the list below,

- [ ] Cleanup attribute value (First step: Get rid of `GenericBlock`)
- [ ] Cleanup how CSharpParser.ParseBlock()` works
- [x] Cleanup MarkupElementRewriter (Original comment: https://github.com/aspnet/Razor/pull/2624#pullrequestreview-160520343)
- [ ] Should we generate classified spans for a tag helper end tag?
- [ ] In cases like `<p class= >`, the attribute value should contain a marker. Currently it is null.
- [ ] Add TagHelperPrefix to generated baselines
- [x] Razor directive descriptors and directive token descriptors should be first class properties on the directive nodes
- [ ] Need to rethink what goes inside `RazorDirectiveBody` (https://github.com/aspnet/Razor/pull/2621#discussion_r230513198)
- [ ] Should we create a new type for significant whitespace? (https://github.com/aspnet/Razor/pull/2621#discussion_r230513846)
- [ ] `@: ` shouldn't be represented as `CSharpTemplateBlock` (https://github.com/aspnet/Razor/pull/2708#discussion_r232419788)
- [ ] Why does `WhitespaceRewriter` exist separately?
- [ ] Generate TagHelperSpans with more information on attributes
- [x] Trailing extensible directive whitespace is considered markup at design time (https://github.com/aspnet/AspNetCore-Internal/issues/1464)
- [ ] Get rid of the remaining few chunk generators

**Comment by mkArtakMSFT** [comment]
@ajaybhargavb what needs to happen here? Can this be closed already?

**Comment by ajaybhargavb** [comment]
This is a full list of all the quality of life improvements we wanted to do to the parser. But at this point the ROI on this is low. I suggest keeping this around in the backlog in case we ending needing to do one or more of these in the future to light up other scenarios. At this point, there are none.

**Comment by mkArtakMSFT** [comment]
Closing this as we should move toward a model where issues are raised based on the measured impact.
