### ISSUE TITLE
[Blazor Web] Docs umbrella issue

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#51580]
I've taken a look at the docs, and I think we need to do a significant rework of the docs over the coming months to put the emphasis on Blazor Web and less on Blazor Server and Web assembly, and to provide the docs with a reasonable structure that enables folks to progressively learn the framework.

* Docs should talk about Blazor Web and put webassembly/server on a less relevant po

Structure for Blazor web docs:
* We need an introduction that explains what Blazor web is. We should market it as the main model in addition to hybrid, and relegate web and server to a secondary role.
* We need a basic article that introduces:
  * Static SSR rendering
  * Forms, validation and model binding.
  * Adding interactivity with Blazor Server and Web assembly
  * Something like https://learn.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-7.0&tabs=visual-studio but much better structured, focused on the fundamentals and happy path and not on specific concrete features/cases.
* We need the docs to be focused on Blazor Web and have a structure that progresses from static server-side rendering to interactive scenarios. Something like:
  * Introduction
  * Tutorial/sample
  * Common:
    * Component model, etc.
    ...
  * Server-side rendering:
    * Routing.
    * Streaming rendering.
    * Enhanced navigation.
    * Form handling.
    * Validation.
    * Model binding.
    * Security (antiforgery).
  * Interactive rendering:
    * Introduction.
    * Render modes.
    * Application models (Client-side routing vs server-side routing).
    * Event handling and other interactivity related topics.

- [ ] https://github.com/dotnet/aspnetcore/issues/51576
- [ ] https://github.com/dotnet/aspnetcore/issues/51575
- [ ] https://github.com/dotnet/aspnetcore/issues/51574
- [ ] https://github.com/dotnet/aspnetcore/issues/51573
- [ ] https://github.com/dotnet/aspnetcore/issues/51572
- [ ] https://github.com/dotnet/aspnetcore/issues/51571
- [ ] https://github.com/dotnet/aspnetcore/issues/51570
- [ ] https://github.com/dotnet/aspnetcore/issues/51569
