### ISSUE TITLE
[Epic]: Support returning values from client invocations

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#5280]
Support server to clients acks so that reliable messaging can be implemented more easily. This would only be when using `Clients.Client()`. I think we should go back to the SendAsync (fire and forget) InvokeAsync (wait for ack) naming pattern. That's the one sticking point.

EDIT by @anurse: For clarity, this issue is tracking all work related to allowing values to be returned from client invocations. It **also** covers allowing the server to wait for a `void`-returning (or `Task`-returning) client side method to complete.

### Work left for .NET 7

- [x] #41777
  - What does an async `.On` method look like? Probably `Single<T>`
- [x] #41996
  ~~This was already an issue with Task returning `.On` methods, but client results likely makes it more likely to block on the client side~~
~~[ ] #41997~~
  - Today we detect if you allow parallel hub invocations and throw if you don't when trying to use the feature. This doesn't work if you use `IHubContext` in the Hub, or if you have multiple waiting results for the same connections Hubs.
  - This is also especially bad in `OnConnectedAsync` because that's a special method that runs before the receive loop starts, we need to throw/unblock/warn etc. for this
~~[ ] Analyzer to warn about strongly-typed hubs and using `InvokeAsync` with `.All`, `.Group`, etc.~~
~~[ ] `InvokeAsync` void result? Scenario, acks without needing a value~~
~~[ ] [Scaleout] ServerA requests client result from connection on ServerB, ServerB goes down after receiving request, ServerA needs to know somehow so it can error the client result~~
- [x] [Scaleout] Consider alternative unique invocation ID generation instead of prepending the connectionID (https://github.com/dotnet/aspnetcore/pull/40811#discussion_r845643262)
~~[ ] Look at performance~~
  ~~The biggest performance issue I can think of right now is that `RawResult` allocates and copy the bytes which can be expensive~~
~~[ ] Flow cancellation from server to client~~
  ~~- Inject `CancellationToken` into `.On` methods and send `CancelInvocation` hub messages to clients~~

**Comment by yasin-uohyd** [comment]
hi @davidfowl , Are we going to release this anytime soon? I'm working on a micro-service orchestration design based on Azure SignalR Service, this feature would make my architecture simple.

**Comment by hodgezappa** [comment]
I have the same need

**Comment by ByronAP** [comment]
another +1 on this

**Comment by willignicolas** [comment]
Still no plan for this ? Thx.

**Comment by kasper112** [comment]
@anurse just to understand will this be add  and can u tell me when ?

**Comment by anurse** [comment]
We have no concrete plan to add this in an upcoming release at this time. We'll consider it during planning for 5.0 but have made no commitment on when we will ship this functionality.

**Comment by alexanderwieland** [comment]
another +1 on this

**Comment by DadonLior** [comment]
another +1 on this

**Comment by MhAllan** [comment]
I like how easy they simply say "no plan to do it" when that "it" is mandatory feature even for a software 20 years ago.

**Comment by kasper112** [comment]
> I like how easy they simply say "no plan to do it" when that "it" is mandatory feature even for a software 20 years ago.

I have to total agree with this statement... it will be a lot more useful to use when u support this feature

**Comment by romanov** [comment]
This feature will provide more clear code. It is sad that we don't have it.

**Comment by yasin-uohyd** [comment]
> It works in 5.0.0.

Let me check that out.

**Comment by hodgezappa** [comment]
> It works in 5.0.0.

do you have a link to the documentation of this feature change?

**Comment by willignicolas** [comment]
Any news ? Is that really in. Net 5? Have you Any documentation link ?

**Comment by wuxiaobo0204** [comment]
Any news ? Is that really in. Net 5? Have you Any documentation link ?

**Comment by davidfowl** [comment]
There's no news, this feature hasn't been implemented

**Comment by rogerfar** [comment]
@davidfowl any plans for .NET 6? We use SignlarR extensively for client/server connections where the server always initiates the connection.

At the moment we just use a simple callback mechanism but it means tracking you lose some of the niceness of SignalR.

**Comment by davidfowl** [comment]
No there are no plans for .NET 6, the team is fully booked. We can put this on the list for .NET 7 though.

**Comment by davidfowl** [comment]
Hey all we're looking at this for .NET 7, can you post interesting scenarios that you doing today that would made easy with client acks/results?

**Comment by rogerfar** [comment]
In our particular case we use our server as a C&C server with multiple clients, all non web related.

We developed a .NET 4.8 client (due to API's that it consumes) that run in DC's of our customers. The app knows how to communicate with certain API's to get data from a system on demand (think ERPs and accounting systems). This app is a SignalR client and connects to the C&C server. It keeps a connection open at all time and listens for commands from given server. We choose SignalR so that our clients don't need to bother with firewalls and open ports, we install it and it connects.

The C&C server needs to be able to request data and wait for the result. Right now we send a command to a specific client, that looks like this:
```
    public class DataRequest
    {
        public Guid RequestId { get; set; }

        public String Request { get; set; }

        public DataResponse Response { get; set; }
    }
```
The invoker adds the transaction in a queue and just sit in a while loop that eventually times out, or waits for the queue to have the `DataResponse` set.

The client responds with something like this, and sends it to a generic signalR function on the C&C server:
```
    public class DataResponse
    {
        public Guid RequestId { get; set; }

        public String Results { get; set; }

        public String Exception { get; set; }
    }
```
We then update the original request in the queue and the original invoker can continue working.

If we can just have SignalR give us a function to wait for a response from the client then we don't need to do this manual queuing process. Something like:
```
var response = await _hubContext.Clients.Client(client.ConnectionId).SendCoreAsync(method,
                                            new Object[]
                                            {
                                                request
                                            });
```

**Comment by DavidErben** [comment]
> Hey all we're looking at this for .NET 7, can you post interesting scenarios that you doing today that would made easy with client acks/results?

Hey David,

we are using SignalR to manage a network of about 1500 IoT nodes (Raspberry Pis). We are invoking methods on the clients to read logs or configuration files, upload data or trigger commands. Right now we use an asynchronous approach so that we create a task object and store it in a database and then send it to the client. The client executes it and sends the response to an API endpoint which sets the status of the task to finished. Currently I am updating the server so that the client directly responds on the SignalR connection, but I need to manually sync tasks/threads to return the response within the same HTTP request (for the caller of my API). It works, but it is a bit clunky.

With return values it would be super easy for us to directly invoke commands on a client node and immediately receive the response. So definitely a +1 from my side for this enhancement.

**Comment by ByronAP** [comment]
I use signalr to maintain proxy connections and much like @DavidErben I too could eliminate a lot of code required to direct responses. 

Client connects to the master node and says I want this address rendered this way the task is completed results put into response db queue then sent back to the client. It's not bad but a lot of code could be eliminated if it was as simple as a client invocation.

**Comment by BrennanConroy** [comment]
# Client Return Values Proposal

Client return values allows invoking a method on the client and waiting for the client to respond in a clean API without writing a bunch of complicated code to generate and pass around message IDs and track TCS's.

Common use cases include clients acknowledging they've received a message and pinging a client for some data.

## High Level Overview

The general idea is to share part of the current HubProtocol and the concept we already have of `InvokeAsync` that the client can call to get a return value from the server.

We can use the `InvocationMessage` and `CompletionMessage` but reverse the direction in order to add support for client results. (Some complications will be discussed below)

We will use the same method naming as the clients `InvokeAsync` because it's already a well known concept that `InvokeAsync` waits for a response and `SendAsync` does not, and it provides consistent naming across the server and client.

`InvokeAsync` will likely hang off of `IClientProxy` so it can be used both in the Hub and outside of the Hub via `IHubContet<THub>`.

The current plan is to only support single client return values. This is because it would be very complicated to have an unopinionated approach that would support getting multiple return values and the API would likely be very unappealing for accessing the values returned.

We will nedd to introduce new methods on `IClientProxy` and `HubLifetimeManager` in order to add support for this, and we can use Default Interface Methods (DIMs) to avoid making a breaking change. Of course 3rd party implementations that haven't added support for the new feature will use the DIMs which will throw a `NotImplementedException` or similar.

## Usage

```csharp
var task1 = _hubContext.Clients.Client(connection1).InvokeAsync<int>("GetNumber");
var task2 = _hubContext.Clients.Client(connection2).InvokeAsync<int>("GetNumber");
res = (await task1) + (await task2);
```

```csharp
hubConnection.On("GetNumber", () =>
{
    return int.Parse(Console.ReadLine());
});
```

## Implementation Details

For the most part the implementation is fairly simple, generate an invocation ID, store a TCS, send an InvocationMessage to the client and wait for the TCS to be completed (via `HubLifetimeManager.InvokeClientAsync()`). The client will send a CompletionMessage with the ID and a result which will trigger the TCS (via `HubLifetimeManager.SetClientResult()`).

Complications show up once we start looking at multi-server scenarios with a backplane.

For current scenarios that involve the backplane we have already considered the problem of deserializing a message from one server on another server; the second server doesn't know the intended type(s) that should be deserialized. We've managed to avoid the issue because the second server has never actually needed to parse the message and instead forwards it to the appropriate client which knows what the expected type(s) are.

However, now that we can receiving messages from a client that are intended for a different server we need to figure out a solution to this problem.

To start with, we are going to rule out deserializing type(s) on the server that is not intended to use the message. This is both for security so we don't need to handle deserializing type(s) we don't know and for perf as the server is just going to forward the message to the appropriate server in the end anyways.
Following this train of thought, we need a way to tell the server to ignore the `CompletionMessage` unless it's the correct server. We could create a type that the `IInvocationBinder` can return that tells the `IHubProtocol` to not parse the `CompletionMessage.Result` and leave it as a `byte[]` unless the message is on the correct server. But this requires a new type that `IHubProtocol`'s need to know about and is very non-obvious. Additionally, we would need a way to get the type information from `HubLifetimeManager` and pass it to `DefaultHubDispatcher` which is currently where `IInvocationBinder` comes from.

A different approach is to create a new message type to add to the protocol, `ClientResultMessage`, which is very similar to the `CompletionMessage` except that its `Result` property will never be deserialized (directly) by the `IHubProtocol` and has a `ProtocolName` property to say what protocol the object stored in the Result was serialized with. The object in `Result` will be the raw bytes of a serialized `CompletionMessage`, and when the `HubLifetimeManager` receives an instance of `ClientResultMessage` it will either forward the `ClientResultMessage.Result` + `ClientResultMessage.ProtocolName` to another server to deal with or it will grab the `Result` property and pass it to the `IHubProtocol` that corresponds to the `ProtocolName` property. The `HubLifetimeManager` would provide an implementation of `IInvocationBinder` that knows the type to be deserialized for the `CompletionMessage.Result` type.

For example the `HubLifetimeManager` will do something like the following when it receives a `ClientResultMessage`:
```csharp
ClientResultMessage resultMessage;
var protocol = _hubProtocolResolver.AllProtocols.First(p => p.Name.Equals(resultMessage.ProtocolName));
var serialized = new System.Buffers.ReadOnlySequence<byte>((byte[])resultMessage.Result);
protocol.TryParseMessage(ref serialized, binder: this, out var message);
Debug.Assert(message is CompletionMessage);
```

## API

```csharp
public class ClientResultMessage : HubMessage
{
    public string? Error { get; }

    // CompletionMessage instance or serialized CompletionMessage
    public object? Result { get; }

    public bool HasResult { get; }

    public string? ProtocolName { get; }
}
```

Only implemented on `SingleClientProxy`:
```diff
public class IClientProxy
{
+    Task<T> InvokeCoreAsync<T>(string method, object?[] args, CancellationToken cancellationToken = default)
+    {
+        throw new NotImplementedException();
+    }
}
```

```diff
public class HubLifetimeManager
{
+    public virtual Task<T> InvokeClientAsync<T>(string connectionId, string methodName, object?[] args, CancellationToken cancellationToken = default)
+    {
+        throw new NotImplementedException();
+    }

+    public virtual Task SetClientResult(ClientResultMessage result)
+    {
+        throw new NotImplementedException();
+    }
}
```

## Final Thoughts

The raw bytes in `ClientResultMessage.Result` is a little hacky, but because `IHubProtocol` has to be the first to look at all bytes from a connection it has to do something without knowing any information about the situation. We could consider making the new message type more generic and will always contain a raw serialized message in the `Result` property which would allow future additions without adding more message types. i.e. `RawResultMessage`

We might want to consider updating the protocol to version 2 if we think this could break old protocols.

By default Hubs only allow a single parallel method invocation per client, using this feature in a Hub method would never be able to receive a result, we should think about this.

Error cases and timeouts are not discussed above, but will need to be once we've committed to a final design.

**Comment by davidfowl** [comment]
`InvokeClientAsync` -> `InvokeConnectionAsync`
`SetClientResult`  -> `SetInvocationResultAsync`

- What about strongly typed clients?
- I don't see the list of client APIs here (we should do JavaScript and C# first)

> We could consider making the new message type more generic and will always contain a raw serialized message in the Result property which would allow future additions without adding more message types. i.e. RawResultMessage

I think I prefer this approach, I'd like to see what it would look like.

**Comment by BrennanConroy** [comment]
> * I don't see the list of client APIs here (we should do JavaScript and C# first)
```csharp
hubConnection.On("GetNumber", () =>
{
    return int.Parse(Console.ReadLine());
});
```
and probably an async version as well
```csharp
hubConnection.On("GetNumber", () =>
{
    return Task.FromResult(int.Parse(Console.ReadLine()));
});
```

**Comment by davidfowl** [comment]
I mean the API definition shape. This example is good though.

**Comment by BrennanConroy** [comment]
Currently have:
```csharp
public static IDisposable On(this HubConnection hubConnection, string methodName, Func<Task<object>> handler)
{
    if (hubConnection == null)
    {
        throw new ArgumentNullException(nameof(hubConnection));
    }

    return hubConnection.On(methodName, Type.EmptyTypes, args => handler());
}
```
But it relies on `as` casting the handler when invoking it. Also haven't looked at if it might conflict with other overloads.

**Comment by BrennanConroy** [comment]
> > We could consider making the new message type more generic and will always contain a raw serialized message in the Result property which would allow future additions without adding more message types. i.e. RawResultMessage
> 
> I think I prefer this approach, I'd like to see what it would look like.

I think it'll look exactly like `ClientResultMessage` but we might want to include another property that identifies what it's for, like `int MessageType { get; }` which would be `HubProtocolConstants.CompletionMessageType` for client results, or maybe a different identifier like a string "client result".

**Comment by BrennanConroy** [comment]
Most of the design has been driven by the difficulty when multiple servers are involved.

In the following diagram Server1 initiates a request for a client result for a client that is connected on a different server.
```mermaid
sequenceDiagram
    Server1->>+Server2: InvocationMessage
    Server2->>+Client1: Forwarded InvocationMessage
    Client1-->>-Server2: CompletionMessage
    Server2-->>-Server1: Forwarded CompletionMessage
```
Without any changes we already have 99% of the work done for the first two steps as we have support for invoking a client method from a different server. The additions needed to add support for return results in the first two steps are, including an `InvocationID` in the message and adding new APIs to initiate a client result. This includes `public virtual Task<T> InvokeClientAsync<T>(string connectionId, string methodName, object?[] args, CancellationToken cancellationToken = default)` on `HubLifetimeManager` and something like `var result = await Clients.Single(connectionId).InvokeAsync<int>("GetNumber");`

For the third step the client needs to add support to its `.On(...)` methods to allow returning a value and sending a `CompletionMessage` to the server. We've already tried it out for Java, Typescript, and .NET clients and adding the new overloads went well.

The fourth step is where things get tricky. There are two main scenarios.
1. Client return result is requested for a client on the same server
2. Client return result is requested for a client on a different server

The main flow looks like:
```mermaid
graph TD
    A[Client CompletionMessage] -->B(Server1)
    B --> C{HubProtocol}
    C <-->|GetType| D[HubLifetimeManager]
    D --> |RawBytes or typeof Response| C
    C -->|CompletionMessage| F[HubLifetimeManager]
    F -->|Is RawBytes| G[Server2]
    F -->|Connection Local| H[Complete pending task]
```
This requires creating a new type `RawBytes` (Placeholder type name for now) and returning that if the server isn't the final destination for the message or returning the expected type from  `Clients.Single(connectionId).InvokeAsync<int>("GetNumber")` if it is the correct server.
When `IHubProtocol` sees `RawBytes` it will need to grab the raw serialized bytes of the `CompletionMessage.Result`and place that in the created `CompletionMessage` as the `Result`. The `HubLifetimeManager` will then call `IHubProtocol.WriteMessage` (with the appropriate IHubProtocol impl of course) with the `CompletionMessage` is got and `IHubProtocol` will know to use the serializers `WriteRaw` when `RawBytes` is seen. It will then forward the serialized `CompletionMessage` to the correct server which will repeat the above flow but get the correct type when calling `GetType`.

The last two pieces of API we need to add are two methods to `HubLifetimeManager`. `public virtual bool TryGetReturnType(string invocationId, [NotNullWhen(true)] out Type? type);` and `public virtual Task SetClientResult(HubConnectionContext sourceConnection, CompletionMessage result)`. The `TryGetReturnType` method is called via `IHubProtocol` when it's trying to get the type to deserialize the `CompletionMessage.Result` and this is what will return `RawBytes` if it needs to route to a different server. And `SetClientResult` is needed so the `HubDispatcher` can give the `CompletionMessage` to the `HubLifetimeManager` so it can complete the waiting user code or forward to another server.

Example code:
```csharp
// JsonHubProtocol
if (type == typeof(RawBytes))
{
    var start = reader.BytesConsumed;
    reader.Skip();
    var end = reader.BytesConsumed;
    var sequence = input.Slice(start, end - start);
    var arr = new byte[sequence.Length];
    sequence.CopyTo(arr);
    return new RawResult(new ReadOnlySequence<byte>(arr));
}
```
```csharp
// RedisHubLifetimeManager
if (_pendingInvocations.TryGetValue(result.InvocationId, out var invocationInfo))
{
    // different server
    if (invocationInfo.CompletionMessage.Result.GetType == typeof(RawBytes))
    {
        var protocolName = connection.Protocol.Name;
        var memoryBufferWriter = MemoryBufferWriter.Get();
        connection.Protocol.WriteMessage(invocationInfo.CompletionMessage, memoryBufferWriter);
        var message = RedisProtocol.WriteCompletionMessage(memoryBufferWriter.ToArray(), protocolName);
        return PublishAsync(invocation.ReturnChannel, message);
    }
    // correct server
    else
    {
        invocationInfo.TCS.SetResult(invocationInfo.CompletionMessage.Result);
    }
}
else
{
    throw new Exception("problem");
}
```

**Comment by BrennanConroy** [comment]
**Client side:**
```diff
class HubConnection
{
    public virtual IDisposable On(string methodName, Type[] parameterTypes, Func<object?[], object, Task> handler, object state)
+   public virtual IDisposable On(string methodName, Type[] parameterTypes, Func<object?[], object, Task<object?>> handler, object state);
}

public static partial class HubConnectionExtensions
{
    public static IDisposable On(this HubConnection hubConnection, string methodName, Type[] parameterTypes, Func<object?[], Task> handler);
    public static IDisposable On<T1>(this HubConnection hubConnection, string methodName, Func<T1, Task> handler);
+   public static IDisposable On<T>(this HubConnection hubConnection, string methodName, Func<Task<T>> handler);
+   public static IDisposable On<T>(this HubConnection hubConnection, string methodName, Func<T> handler);
+   public static IDisposable On<T, T1>(this HubConnection hubConnection, string methodName, Func<T1, T> handler);
+   public static IDisposable On<T, T1>(this HubConnection hubConnection, string methodName, Func<T1, Task<T>> handler);
+   public static IDisposable On<T, T1, T2>(this HubConnection hubConnection, string methodName, Func<T1, T2, Task<T>> handler);
    // etc...
}
```

**Server side:**
```diff
+ public interface ISingleClientProxy : IClientProxy
+ {
+     Task<T> InvokeCoreAsync<T>(string method, object?[] args, CancellationToken cancellationToken = default) => throw new NotImplementedException();
+ }

public interface IHubClients<T>
{
+   T Single(string connectionId) => throw new NotImplementedException();
    T All { get; }
    T AllExcept(IReadOnlyList<string> excludedConnectionIds);
    T Client(string connectionId);
    T Clients(IReadOnlyList<string> connectionIds);
    T Group(string groupName);
    T Groups(IReadOnlyList<string> groupNames);
    T GroupExcept(string groupName, IReadOnlyList<string> excludedConnectionIds);
    T User(string userId);
    T Users(IReadOnlyList<string> userIds);
}

public interface IHubClients : IHubClients<IClientProxy>
{
+   new ISingleClientProxy Single(string connectionId) => throw new NotImplementedException();
}

public interface IHubCallerClients : IHubCallerClients<IClientProxy>
{
+   new ISingleClientProxy Single(string connectionId) => throw new NotImplementedException();
}

public static class ClientProxyExtensions
{
    public static Task SendAsync(this IClientProxy clientProxy, string method, CancellationToken cancellationToken = default);
    public static Task SendAsync(this IClientProxy clientProxy, string method, object? arg1, 
CancellationToken cancellationToken = default);
    // etc...

+   public static Task<T> InvokeAsync<T>(this ISingleClientProxy clientProxy, string method, CancellationToken cancellationToken = default);
+   public static Task<T> InvokeAsync<T>(this ISingleClientProxy clientProxy, string method, object? arg1, CancellationToken cancellationToken = default);
    // etc...
}

public abstract class HubLifetimeManager<THub> where THub : Hub
{
    public abstract Task SendAllAsync(string methodName, object?[] args, CancellationToken cancellationToken = default);
    public abstract Task SendConnectionAsync(string connectionId, string methodName, object?[] args, CancellationToken cancellationToken = default);

+   public virtual Task<T> InvokeConnectionAsync<T>(string connectionId, string methodName, object?[] args, CancellationToken cancellationToken = default) => throw new NotImplementedException();

+   public virtual Task SetConnectionResultAsync(string connectionId, CompletionMessage result) => throw new NotImplementedException();

+   public virtual bool TryGetReturnType(string invocationId, [NotNullWhen(true)] out Type? type)
+   {
+       type = null;
+       return false;
+   }
}

namespace Microsoft.AspNetCore.SignalR.Protocol;
+ public class RawResult
+ {
+     public RawResult(ReadOnlySequence<byte> rawBytes);
+     public ReadOnlySequence<byte> RawSerializedData { get; private set; }
+ }
```

**Comment by davidfowl** [comment]
cc @vicancy

**Comment by davidfowl** [comment]
Should we expose ValueTask\<T\> instead of Task\<T\>?

**Comment by BrennanConroy** [comment]
For the client side API? It would either be wrapped by a Task internally anyways or make it a bit of a pain to implement the internals since it's all Task based for the current `.On` overloads.

**Comment by davidfowl** [comment]
So you think we should stick with Task everywhere?

**Comment by halter73** [comment]
- Let's use the `Func` naming and ordering of type params.
```diff
+   public static IDisposable On<T1, T2, TResult>(this HubConnection hubConnection, string methodName, Func<T1, T2, Task<TResultt>> handler);
```
- Let's keep using `Task` over `ValueTask`.
- Should we just hide `Caller` and `Client` instead of adding `Single`?
```diff
public interface IHubClients : IHubClients<IClientProxy>
{
+   new ISingleClientProxy Client(string connectionId) => throw new NotImplementedException();
}

public interface IHubCallerClients : IHubCallerClients<IClientProxy>
{
+   new ISingleClientProxy Caller => throw new NotImplementedException();
+   new ISingleClientProxy Client(string connectionId) => throw new NotImplementedException();
}
```

Let's keep iterating on this design.

**Comment by davidfowl** [comment]
> Should we just hide Caller and Client instead of adding Single?

This is the only one I'm iffy about. Maybe it's fine? Have you found all of the edge cases? What happens when you inject `IHubClients<T>` and use Client? Does that still work?

**Comment by BrennanConroy** [comment]
> What happens when you inject `IHubClients<T>` and use Client?

Not sure what you mean by inject `IHubClients`, that type isn't in DI by default, and if it was, SignalR isn't going to use your type.

`IHubContext` is in DI and it exposes `IHubClients` so in theory you can provide your own impl of `IHubContext` that uses your own impl of `IHubClients`.

The main thing I've found so far is that when implementing `IHubClient` (or any of the interfaces that hide the base Single or Client methods) you don't get Single or Client with ISingleClientProxy with `ctrl-.`. This is because they both have default implementations (to be non-breaking). So you need to know to implement it,
`ISingleClientProxy IHubClients.Client(string connectionId) => ...;`
or
`ISingleClientProxy IHubClients.Single(string connectionId) => ...;`

**Comment by BrennanConroy** [comment]
The initial iteration of client return results is out.

### Users

To use this new feature there are changes you need to make on the server side and the client side.
On the server you need to use the new APIs on IHubContext or IHubCallerClients.

```csharp
IHubContext<MyHub> context;
int arg = 10;
string result = await context.Single(connectionID).InvokeAsync<string>("ClientMethodName", arg);
```

or inside a Hub method, the caveat here is that you need to set the [`MaximumParallelInvocationsPerClient`](https://docs.microsoft.com/aspnet/core/signalr/configuration?view=aspnetcore-6.0&tabs=dotnet#configure-server-options) option on the server to be greater than 1, and there are still some issues with this that we're working through in later previews:
```csharp
public async Task HubMethod(string connectionId)
{
    int arg = 11;
    string result = await Clients.Single(connectionId).InvokeAsync<string>("ClientMethodName", arg);
}
```

Additionally, strongly-typed hubs can be used so now your interfaces can return a value and be used:
```csharp
public interface IClient
{
    Task<string> Send(int arg);
}

public class HubT : Hub<IClient>
{
    public async Task HubMethod(string connectionId)
    {
        int arg = 12;
        string result = await Clients.Single(connectionId).Send(arg);
    }
}
```

And on the client you need to return a value from your `.On(...)` method:
.NET Client:
```csharp
hubConnection.On("ClientMethodName", (int someArg) =>
{
    return someArg.ToString();
});
```
TypeScript Client:
```typescript
hubConnection.on("ClientMethodName", arg => {
    return `${arg}`;
});
```

### HubLifetimeManager implementors

Three new methods have been added to HubLifetimeManager, they have default implementations (that throw NotImplementedExcetion) so that it's not a breaking change to consume the new bits. Additionally, if the implementation of HubLifetimeManager communicates with other servers then you will need to be aware of the `RawResult` type which is used to pass the raw serialized bytes of a clients payload to another server without needed to fully deserialize the payload on the intermediary server.

```diff
public abstract class HubLifetimeManager<THub> where THub : Hub
{
+    public virtual Task<T> InvokeConnectionAsync<T>(string connectionId, string methodName, object?[] args, CancellationToken cancellationToken = default);
+    public virtual Task SetConnectionResultAsync(string connectionId, CompletionMessage result);
+    public virtual bool TryGetReturnType(string invocationId, [NotNullWhen(true)] out Type? type);
}
```

### IHubProtocol implementors

The main change needed for `IHubProtocol` is to handle the `RawResult` type. `IInvocationBinder.GetReturnType(string invocationID)` can return `RawResult` which means don't deserialize the result and instead store the raw bytes of the result in the `RawResult` type. And when serializing the payload if a `RawResult` type is being written write the raw bytes as if they were already serialized.

Example:
Receiving Json of `{"type":3,"result":34,"invocationId":"1234"}` and seeing that result is `RawResult` will mean don't try to deserialize 34 as an int or anything and instead store the bytes `[(byte)'3', (byte)'4']` in a `RawResult` object. And when writing the Json of this `RawResult` object you wouldn't serialize the `byte[]` as that would base64 encode the value, you instead directly write `(byte)'3'` and `(byte)'4'` to the output.

### Work left for .NET 7

- [ ] Add Java client implementation for client results
  - What does an async `.On` method look like? Probably `Single<T>`
- [ ] `HubConnection.On` w/return results blocks client receive pipeline
  - This was already an issue with Task returning `.On` methods, but client results likely makes it more likely to block on the client side
- [ ] `InvokeAsync` in Hub methods can soft-lock the connection
  - Today we detect if you allow parallel hub invocations and throw if you don't when trying to use the feature. This doesn't work if you use `IHubContext` in the Hub, or if you have multiple waiting results for the same connections Hubs.
- [ ] Analyzer to warn about strongly-typed hubs and using `InvokeAsync` with `.All`, `.Group`, etc.
- [ ] `InvokeAsync` void result? Scenario, acks without needing a value
- [ ] [Scaleout] ServerA requests client result from connection on ServerB, ServerB goes down after receiving request, ServerA needs to know somehow so it can error the client result
- [ ] [Scaleout] Consider alternative unique invocation ID generation instead of prepending the connectionID (https://github.com/dotnet/aspnetcore/pull/40811#discussion_r845643262)
- [ ] Look at performance
  - The biggest performance issue I can think of right now is that `RawResult` allocates and copy the bytes which can be expensive

**Comment by Aloento** [comment]
I'm having an issue where I can't seem to return messages from the C# client.
Calling the client method in `OnConnectedAsync` and waiting for the return, the client can already see the return request, but the server keeps waiting. 
`7.0.0-preview.4.22251.1`  with `JSON` or `MessagePack`

**Comment by BrennanConroy** [comment]
Ah yeah, thought about that scenario but didn't look into it. It's not going to work and likely never will work because of how OnConnectedAsync is called.

**Comment by Aloento** [comment]
uh…ok, so maybe someone can mention this in the document.

**Comment by BrennanConroy** [comment]
Yep, we'll either document it somewhere or see if we can make it error. Added it to the list above.

**Comment by halter73** [comment]
I agree that this should be documented. I think it's even more important to just throw an `InvalidOperationException` immediately if someone tries to do this.

**Comment by DavidErben** [comment]
> 
>     * [ ]  `HubConnection.On` w/return results blocks client receive pipeline
>       
>       * This was already an issue with Task returning `.On` methods, but client results likely makes it more likely to block on the client side
>         
>         * .NET client blocks other `.On` handlers but does not block the receive loop

Hey guys, I just tried this out with .NET 7 RC1 and the methods are still blocking (like before if one returned a Task). Are there any plans to change this behavior for the official .NET 7 release?

We are using this feature to trigger commands on connected IoT devices. Usually a bunch of commands are triggered simultaneously, so it would be cool if they would run in parallel. But if it is not possible it is not a huge deal either.

**Comment by halter73** [comment]
> Hey guys, I just tried this out with .NET 7 RC1 and the methods are still blocking (like before if one returned a Task). Are there any plans to change this behavior for the official .NET 7 release?

Done. #44014
