### ISSUE TITLE
[Epic] SignalR should have a C++ client

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#5301]
* [x] https://github.com/aspnet/AspNetCore/issues/8719 vcpkg support
* [x] https://github.com/aspnet/AspNetCore/issues/8718 cpprestsdk-less build option
* [x] https://github.com/aspnet/AspNetCore/issues/8706 Cross-platform, MSBuild-integrated Build
* [ ] https://github.com/aspnet/AspNetCore/issues/8716 Options/Config/Auth
* [x] https://github.com/aspnet/AspNetCore/issues/8715 Hub Protocol Abstraction
* [x] https://github.com/aspnet/AspNetCore/issues/8721 Pinging/Timeouts
* [ ] https://github.com/aspnet/AspNetCore/issues/8717 Public API Review
* [ ] https://github.com/aspnet/AspNetCore/issues/8720 Client Cleanup

**Comment by stukselbax** [comment]
Will this client be compatible with aspnetcore signalr 2.1-2.2 server?

Probably the [SignalR/clients/cpp/README.md](https://github.com/aspnet/AspNetCore/blob/master/src/SignalR/clients/cpp/README.md) and [docs](https://docs.microsoft.com/en-us/aspnet/core/signalr/supported-platforms?view=aspnetcore-3.0#unsupported-clients) should be updated to point out your plans about the C++ client.

**Comment by BrennanConroy** [comment]
Yes this will be compatible with AspNetCore SignalR

**Comment by wegylexy** [comment]
any idea why `get_connection_id()` on client doesn't match with `Context.ConnectionId` on server?

**Comment by BrennanConroy** [comment]
We are just starting to work on this. I'd suggest giving us a few weeks to make some progress and then start filing issues :)

Glad you're trying it out though!

**Comment by pps83** [comment]
A few questions regarding c++ signalr client:
 - how different is the old signalr from asp.net core signalr? Where can I read to understand these differences and why these two are incompatible?
 - signalr uses cpprestsdk, which isn't a tiny lib. In our case we cannot use it because of the binary size. Would that be easy to make a lean version of signalr that does only websockets (without pure http fallback)?

**Comment by wegylexy** [comment]
When linked statically, the final binary is small, meaning I'm using only a tiny bit of cpprestsdk. But there were a lot of trials and errors to finally got everything compiled and linked. Preferably there will be a small signalrclient.lib and signalrclient.dll that doesn't require any other DLLs at run-time.

**Comment by pps83** [comment]
I'll check size impact of signalr, but we weren't able to ship it due to app store size limits (we are a large 100mb-range app)

**Comment by steji113** [comment]
Speaking of using cpprestsdk, I had started a conversation last year regarding other library options back on aspnet/signalr#2510. It looks like this issue had some other good tidbits of feedback that might still be valuable, as well.

I am still interested in any potential API discussions too.

**Comment by steji113** [comment]
Just following up on this as I see the C++ client is being actively worked on. /cc @anurse since I originally chatted with you. Also, /cc @BrennanConroy as I believe you are the one actively working on it and might have some insight into the design process. Thanks guys!

**Comment by BrennanConroy** [comment]
Hey @steji113, we're currently working on cleaning up the API to not use any external libraries publicly. The big one right now is `pplx::task<T>` and we're looking at doing a callback model. For example invoke might look like `connection.invoke("MethodName", args, [](some_param) { // process params });`

**Comment by alexsandro-xpt** [comment]
Anybody know what is the roadmap for this library?

**Comment by BrennanConroy** [comment]
We are planning on shipping alongside the 3.0 release.

**Comment by anurse** [comment]
We need to break this up into smaller issues ASAP, I'll check in with you @BrennanConroy.

**Comment by alexsandro-xpt** [comment]
@BrennanConroy The ASPNET Core 3.0 release is planned to end of this year but I would like to start test something. Can I using this project https://github.com/aspnet/SignalR-Client-Cpp to test?

**Comment by BrennanConroy** [comment]
Our priorities have changed and I can't guarantee that this will ship in the 3.0 release.

https://github.com/aspnet/SignalR-Client-Cpp is where we will be doing work on the C++ client. Feel free to test it out and file issues in this repo.

**Comment by proga7med** [comment]
- Does signalr support a hub proxy? I can't see the hub proxy class

**Comment by anurse** [comment]
No, the Hub Proxy mechanism is no longer present in the SignalR client. Instead you call `.InvokeAsync("NameOfMethod", arg1, arg2)` on the `HubConnection`. By the way, this issue is tracking our work on a C++ client, I'd suggest posting a separate issue if you have a general SignalR question, or asking on [Stack Overflow](https://stackoverflow.com/).
