### ISSUE TITLE
Mod Rewrite Middleware Checklist

### ISSUE THREAD

**Issue by jkotalik** [dotnet/aspnetcore#5982]
**Features implemented in mod_rewrite:**
Types:
- [x] RewriteCond
- [x] RewriteRule

Flags:
- [x] Cookie
- [x] Escape Back References
- [x] End
- [x] Forbidden
- [x] Gone
- [x] Last
- [x] No Case
- [x] Query String Append
- [x] Query String Delete
- [x] Redirect

Server Variables:
- [x] HTTP_ACCEPT
- [x] HTTP_COOKIE
- [x] HTTP_FORWARDED
- [x] HTTP_HOST
- [x] HTTP_REFERER
- [x] HTTP_USER_AGENT
- [x] CONN_REMOTE_ADDR
- [x] QUERY_STRING
- [x] REMOTE_ADDR
- [x] IPV6
- [x] REMOTE_PORT
- [x] REQUEST_METHOD
- [x] SCRIPT_FILENAME
- [x] SERVER_ADDR
- [x] SERVER_PORT
- [x] SERVER_PROTOCOL
- [x] TIME_YEAR
- [x] TIME_MON
- [x] TIME_DAY
- [x] TIME_HOUR
- [x] TIME_MIN
- [x] TIME_SEC
- [x] TIME_WDAY
- [x] TIME
- [x] HTTPS
- [x] REQUEST_FILENAME
- [x] REQUEST_SCHEME
- [x] REQUEST_URI

CondPattern:
- [x] Integer Comparison
- [x] String Comparison
- [x] Is File
- [x] Is Directory
- [x] Size

**Features that are not implemented in mod_rewrite:**
Types:
- [ ] RewriteBase
- [ ] RewriteMap
- [ ] RewriteEngine

Flags:
- [ ] Chain
- [ ] Discard Path
- [ ] Env
- [ ] Next
- [ ] No Escape
- [ ] Pass Through
- [ ] Query String Last
- [ ] Skip

Server Variables:
- [ ] PATH_INFO

CondPattern:
- [ ] Symbolic Link

**Features that will most likely not be implemented (not supported)**
Types:
- [ ] RewriteOptions

Flags:
- [ ] Handler
- [ ] No Subrequest
- [ ] No Vary
- [ ] Proxy
- [ ] Type

Server Variables:
- [ ] HTTP_PROXY_CONNECTION
- [ ] AUTH_TYPE
- [ ] CONTEXT_PREFIX
- [ ] CONTEXT_DOCUMENT_ROOT
- [ ] REMOTE_HOST
- [ ] REMOTE_IDENT
- [ ] REMOTE_USER
- [ ] DOCUMENT_ROOT
- [ ] SCRIPT_GROUP
- [ ] SCRIPT_USER
- [ ] SERVER_ADMIN
- [ ] SERVER_NAME
- [ ] SERVER_SOFTWARE
- [ ] API_VERSION
- [ ] CONN_REMOTE_ADDR
- [ ] IS_SUBREQ
- [ ] REMOTE_ADDR
- [ ] THE_REQUEST
- [ ] Segmented Lookups (Ex HTTP:header) 

CondPattern:
- [ ] Existing Url via subrequest
- [ ] Executable
